var questions = [{'Question': '"Dead End Street" By The Kinks Was Originally Released 1962, 1966, 1968?', 'Answer': 1966.0} ,
{'Question': '13:00 czasu wojskowego to ile godzin?', 'Answer': 1300.0} ,
{'Question': '11 am W czasie wojskowym jest ile godzin?', 'Answer': 1100.0} ,
{'Question': '11:37 pm W czasie wojskowym jest ile godzin?', 'Answer': 2337.0} ,
{'Question': '1k równa się ile bajtów?', 'Answer': 1024.0} ,
{'Question': '2 + 5 x 6 = ?', 'Answer': 32.0} ,
{'Question': '17:45 W czasie wojskowym jest ile godzin?', 'Answer': 1745.0} ,
{'Question': '19:25 czasu wojskowego jest ile godzin?', 'Answer': 1925.0} ,
{'Question': 'Godzina 21:00 czasu wojskowego to ile godzin?', 'Answer': 2100.0} ,
{'Question': 'Na planszy do gry w backgammona wypisano piłokształtne "punkty" w dwóch kolorach. Ile jest tych punktów?', 'Answer': 24.0} ,
{'Question': 'Gracz w warcaby zaczyna z iloma pionkami?', 'Answer': 12.0} ,
{'Question': 'W którym roku piosenka "Boogie Oogie Oogie" zespołu A Taste of Honey była wielkim przebojem?', 'Answer': 1978.0} ,
{'Question': 'Amerykańska dziesięciocentówka jest warta ___ centów.?', 'Answer': 10.0} ,
{'Question': 'Puszka Pepsi zawiera __ uncji płynu.?', 'Answer': 12.0} ,
{'Question': 'Ile mięśni ma kot w każdym uchu?', 'Answer': 32.0} ,
{'Question': 'Kaszel uwalnia wybuchowy ładunek powietrza, który porusza się z prędkością do ilu mil na godzinę.?', 'Answer': 60.0} ,
{'Question': 'Ile szklanek mleka daje krowa w ciągu swojego życia?', 'Answer': 200000.0} ,
{'Question': 'Jak wiele grzbietów wokół krawędzi ma dziesięciocentówka?', 'Answer': 118.0} ,
{'Question': 'Ile razy pchła może przeskoczyć swoją własną długość?', 'Answer': 100.0} ,
{'Question': 'Linijka długa na stopę ma __ cali długości.?', 'Answer': 12.0} ,
{'Question': 'Ile litrów ma magnum szampana?', 'Answer': 1.5} ,
{'Question': 'Kret może wykopać tunel o długości __________ stóp w ciągu jednej nocy.?', 'Answer': 300.0} ,
{'Question': 'W którym roku pod stadionem piłkarskim w Chicago zbudowano reaktor jądrowy?', 'Answer': 1942.0} ,
{'Question': 'Nosorożec ma __________ palców u każdej stopy.?', 'Answer': 3.0} ,
{'Question': 'Krewetka ma __________ par odnóży.?', 'Answer': 5.0} ,
{'Question': 'Krewetka ma ponad sto par chromosomów w każdym jądrze komórkowym. Człowiek ma tylko __________.?', 'Answer': 23.0} ,
{'Question': 'Ile kul potrzeba do gry w snookera?', 'Answer': 22.0} ,
{'Question': 'W którym roku w Chinach w pożarze teatru zginęło łącznie 1670 osób?', 'Answer': 1845.0} ,
{'Question': 'Ile świń zjada przeciętny Amerykanin w ciągu swojego życia?', 'Answer': 28.0} ,
{'Question': 'Zdolność wilka do wykrywania zapachów jest __________ razy większa niż człowieka.?', 'Answer': 100.0} ,
{'Question': 'AQOS jest obecnie najdłużej działającym quizem sportowym w telewizji, kiedy został po raz pierwszy wyemitowany? 1969, 1970, 1971,1972?', 'Answer': 1970.0} ,
{'Question': 'W którym roku został zbudowany pierwszy statek parowy?', 'Answer': 1787.0} ,
{'Question': 'Ile dziur potrzeba, aby wypełnić Albert Hall?', 'Answer': 4000.0} ,
{'Question': 'Według piosenki Ilu było perkusistów grających na bębnach?', 'Answer': 12.0} ,
{'Question': 'Ile lat według Biblii żył Metuzelah?', 'Answer': 969.0} ,
{'Question': 'Według brytyjskiego Narodowego Biura Meteorologicznego w którym roku (przed 2007) było ostatnie Białe Boże Narodzenie w Wielkiej Brytanii?', 'Answer': 2004.0} ,
{'Question': 'Ile lat trwa "Rok samotności", jak brzmi tytuł znanej powieści?', 'Answer': 100.0} ,
{'Question': 'Aktor Arnold Schwarzenegger kupił pierwszego Hummera wyprodukowanego do użytku cywilnego, kiedy?', 'Answer': 1992.0} ,
{'Question': 'Admirał Donitz zastąpił Hitlera w którym roku?', 'Answer': 1945.0} ,
{'Question': 'W którym roku Adolf Hitler został kanclerzem Niemiec?', 'Answer': 1933.0} ,
{'Question': 'Po ilu latach małżeństwa obchodzisz szmaragdową rocznicę ślubu?', 'Answer': 55.0} ,
{'Question': 'Po II wojnie światowej, w którym roku zakończono reglamentację odzieży?', 'Answer': 1949.0} ,
{'Question': 'W którym roku, po latach flirtów, USA rozpoczęły bezpośrednie zaangażowanie wojskowe w Wietnamie?', 'Answer': 1964.0} ,
{'Question': 'W którym roku Agatha Christie zaginęła na 10 dni?', 'Answer': 1926.0} ,
{'Question': 'Wszystkie zostały wydane w którym roku: "Anarchy In The Uk", "Fernando", "A Star Is Born".?', 'Answer': 1976.0} ,
{'Question': 'Kwota, którą Beatlesi otrzymali za występ w Ed Sullivan Show?', 'Answer': 3500.0} ,
{'Question': 'Amundsen dotarł na biegun południowy w którym roku?', 'Answer': 1911.0} ,
{'Question': 'Ile galonów wody wypija przeciętny człowiek w ciągu życia?', 'Answer': 16000.0} ,
{'Question': 'Około 800 osób zginęło podczas pokazu fajerwerków w Paryżu w którym roku?', 'Answer': 1770.0} ,
{'Question': 'Ile mniej więcej ziaren kawy składa się na miarkę ekspresu?', 'Answer': 40.0} ,
{'Question': 'Ile mniej więcej dzieci spłodził faraon Ramzes II?', 'Answer': 160.0} ,
{'Question': 'Ile mniej więcej koncertów skomponował Antonio Vivaldi?', 'Answer': 500.0} ,
{'Question': 'Ile mniej więcej genów znajduje się na jednej cząsteczce ludzkiego DNA?', 'Answer': 80.0} ,
{'Question': 'W przybliżeniu, ile cali jest w metrze?', 'Answer': 39.0} ,
{'Question': 'Ile cali jest w przybliżeniu w jednym metrze?', 'Answer': 39.0} ,
{'Question': 'Ile funtów płatków śniadaniowych zjada rocznie przeciętny Amerykanin/Kanadyjczyk?', 'Answer': 12.0} ,
{'Question': 'Jaki procent powierzchni Ziemi pokrywają w przybliżeniu oceany?', 'Answer': 71.0} ,
{'Question': 'Gdy prędkość ciała zbliża się do prędkości światła, jego masa zbliża się do ________?', 'Answer': 'nieskończoność'} ,
{'Question': 'W jakim wieku Michael Jackson nagrał "Got To Be There"?', 'Answer': 13.0} ,
{'Question': 'W którym momencie skale temperatury Fahrenheita i Celcjusza pokrywają się?', 'Answer': -40.0} ,
{'Question': 'Ile sztuk ma każdy z graczy na początku gry w przeciąganie?', 'Answer': 12.0} ,
{'Question': 'W jakim wieku gracz może dołączyć do Seniors Golf Tour 45, 50 lub 55 lat?', 'Answer': 50.0} ,
{'Question': 'W jakim wieku Will Carling po raz pierwszy został kapitanem Anglii?', 'Answer': 22.0} ,
{'Question': 'Na której olimpiadzie Zola Budd przypadkowo potrącił Mary Decker?', 'Answer': 1984.0} ,
{'Question': 'Awokado ma najwięcej kalorii spośród wszystkich owoców - ___ kalorii na sto gramów?', 'Answer': 167.0} ,
{'Question': 'BSE zostało zidentyfikowane w Wielkiej Brytanii w którym roku?', 'Answer': 1986.0} ,
{'Question': 'Beat It" Michaela Jacksona został singlem roku. Który to był rok?', 'Answer': 1983.0} ,
{'Question': "Betty Boo robiła 'the doo' w którym roku?", 'Answer': 1990.0} ,
{'Question': 'Beverly hills ma jaki fikcyjny kod pocztowy?', 'Answer': 90210.0} ,
{'Question': 'Billy the Kid urodził się w _____?', 'Answer': 1859.0} ,
{'Question': 'Birdseye" wprowadził paluszki rybne do Wielkiej Brytanii w którym roku?', 'Answer': 1955.0} ,
{'Question': 'W którym roku rozpoczęto budowę opactwa westminsterskiego?', 'Answer': 1050.0} ,
{'Question': 'Do 70 roku życia przeciętny człowiek zrzuci ile kilogramów skóry?', 'Answer': 105.0} ,
{'Question': 'Do czasu ukończenia przez dziecko szkoły podstawowej będzie ono świadkiem ilu aktów przemocy w telewizji?', 'Answer': 100000.0} ,
{'Question': 'Zanim dziecko ukończy szkołę podstawową, będzie świadkiem ilu morderstw w telewizji?', 'Answer': 8000.0} ,
{'Question': 'Koty mają ponad sto dźwięków głosowych, podczas gdy psy mają tylko około __________?', 'Answer': 10.0} ,
{'Question': 'Koty, a nie psy, są obecnie najbardziej rozpowszechnionymi zwierzętami domowymi w Ameryce. Około 66 milionów kotów do 58 milionów psów to zwierzęta rodzinne, a papużki "latające" są na dalekim trzecim miejscu pod adresem __________.?', 'Answer': 14000000.0} ,
{'Question': 'Charles l został postawiony przed sądem w którym roku?', 'Answer': 1649.0} ,
{'Question': 'Charlie Chaplin zmarł w Boże Narodzenie w 1977 roku, ile miał lat, kiedy zmarł?', 'Answer': 88.0} ,
{'Question': 'W którym roku Christian Dior zaprezentował swój "Nowy Wygląd"?', 'Answer': 1947.0} ,
{'Question': 'Coco-cola" została wynaleziona w którym roku?', 'Answer': 1886.0} ,
{'Question': 'Kontrowersyjny guru diety nathan pritikin umiera w nowojorskim szpitalu w wieku?', 'Answer': 69.0} ,
{'Question': 'Płatki kukurydziane zostały wynalezione w którym roku: 1863, 1890 czy 1915?', 'Answer': 1890.0} ,
{'Question': 'Kuguary mogą zabijać zwierzęta __________ razy większe od siebie?', 'Answer': 8.0} ,
{'Question': 'W którym roku ukazała się pierwsza powieść Daniela Defoesa?', 'Answer': 1719.0} ,
{'Question': 'W którym roku Dario Fo otrzymał literacką Nagrodę Nobla?', 'Answer': 1997.0} ,
{'Question': 'Disney World na Florydzie został otwarty dla publiczności w 1971 roku. Był to największy park rozrywki na świecie, położony na obszarze ________ akrów. Wymagał zainwestowania 400 milionów dolarów i nie radził sobie dobrze w pierwszym roku działalności.?', 'Answer': 28000.0} ,
{'Question': 'Disneyland został otwarty w którym roku?', 'Answer': 1955.0} ,
{'Question': 'Duran Duran byli "dzikimi chłopcami" którego roku?', 'Answer': 1984.0} ,
{'Question': 'Ile chromosomów zawiera każda komórka ciała?', 'Answer': 46.0} ,
{'Question': 'Ed Moses zdobył tytuł mistrzowski w biegu na 400 metrów przez płotki w którym roku?', 'Answer': 1984.0} ,
{'Question': 'W którym roku po raz pierwszy użyto elektrycznych lampek choinkowych? 1878,1895, 1903, 1907?', 'Answer': 1895.0} ,
{'Question': 'Angielska lista przebojów: Clive Dunn miał hit o nazwie Grandad w którym roku?', 'Answer': 1971.0} ,
{'Question': 'Ferdinand i Imelda Marcos zostali wygnani w którym roku?', 'Answer': 1986.0} ,
{'Question': 'Tytuł filmu: Fahrenheit ________. (a number)?', 'Answer': 451.0} ,
{'Question': 'Film Title: ______ (a number) Leagues Under the Sea.?', 'Answer': 20000.0} ,
{'Question': 'Tytuł filmu: "______ leagues under the sea".?', 'Answer': 20000.0} ,
{'Question': 'Tytuł filmu " ______, a space odyssey?', 'Answer': 2001.0} ,
{'Question': 'Tytuł filmu" "fahrenheit ______?', 'Answer': 451.0} ,
{'Question': 'W którym roku Florence została poważnie zalana?', 'Answer': 1966.0} ,
{'Question': 'Dla ilu rozgłośni radiowych zaliczono "imaginary landscaper no 4" Johna Cage\'a?', 'Answer': 12.0} ,
{'Question': 'Za ile amerykański urolog kupił penisa Napoleona? (w dolarach amerykańskich)?', 'Answer': 3800.0} ,
{'Question': 'Z farm krokodyli Australia eksportuje rocznie ok. 5 tys. krokodylich skór. Większość trafia do Paryża, gdzie torebka z krokodyla może być sprzedana za więcej niż __________.?', 'Answer': 10000.0} ,
{'Question': 'Z którego peronu odjeżdża pociąg "Chattanooga Choo Choo" ze stacji Pennsylvania?', 'Answer': 29.0} ,
{'Question': 'Z jakiego peronu odjeżdża "chattanooga choo choo" ze stacji Pennsylvania?', 'Answer': 29.0} ,
{'Question': 'W którym roku Kaddafi doszedł do władzy?', 'Answer': 1969.0} ,
{'Question': 'George Michaels "Father Figure" został wydany w 1986 lub 1988 roku?', 'Answer': 1988.0} ,
{'Question': 'W którym roku urodził się George Stephenson?', 'Answer': 1781.0} ,
{'Question': 'W którym roku George Washington został pierwszym prezydentem Stanów Zjednoczonych?', 'Answer': 1789.0} ,
{'Question': 'Biorąc pod uwagę 10 lat w każdą stronę, w którym roku powstała Mona Lisa?', 'Answer': 1503.0} ,
{'Question': 'Biorąc pod uwagę 5 lat, w którym roku Sir Francis Drake rozpoczął swoją podróż dookoła świata?', 'Answer': 1577.0} ,
{'Question': 'W którym roku Glascow zostało wybrane Europejskim Miastem Kultury?', 'Answer': 1990.0} ,
{'Question': 'Going Undergound" był hitem zespołu The Jam w którym roku?', 'Answer': 1980.0} ,
{'Question': 'Wielka Brytania była pierwszym krajem, który wydał znaczki pocztowe, ale w którym roku?', 'Answer': 1840.0} ,
{'Question': 'W tym roku został założony Harvard College?', 'Answer': 1636.0} ,
{'Question': 'Hirohito wstąpił na japoński tron w którym roku?', 'Answer': 1926.0} ,
{'Question': 'Jego czwarty sukces na listach przebojów Kiedy "Crocodile Rock" stał się hitem Eltona Johna?', 'Answer': 1972.0} ,
{'Question': 'W którym roku Holandia była gospodarzem Igrzysk Olimpijskich?', 'Answer': 1928.0} ,
{'Question': 'Hotel California" zespołu The Eagles został singlem roku, a "Rumours" Fleetwood Mac albumem roku. Który to był rok?', 'Answer': 1977.0} ,
{'Question': "Jak liczba binarna '010' jest wyrażona w systemie dziesiętnym?", 'Answer': 2.0} ,
{'Question': 'Jaką długość w milach ma maraton?', 'Answer': 26.0} ,
{'Question': 'Ile bitów jest w bajcie?', 'Answer': 8.0} ,
{'Question': 'How Many Bridges Are There in St Petersburg?', 'Answer': 365.0} ,
{'Question': 'How Many Chart Entries Did The Jam Have Between March & August 1980 (2,4,6 Or 8)?', 'Answer': 8.0} ,
{'Question': 'Ile pazurów ma kot domowy?', 'Answer': 18.0} ,
{'Question': 'Z ilu kolorów składa się tęcza?', 'Answer': 7.0} ,
{'Question': 'Ile kolejnych No.1 mieli The Beatles w latach 1963-1966?', 'Answer': 11.0} ,
{'Question': 'Ile tytułów singlowych z rzędu na Wimbledonie zdobył Bjorn Borg?', 'Answer': 5.0} ,
{'Question': 'Ile tytułów singlowych z rzędu w Wimbledonie zdobył Bjorn Borg?', 'Answer': 5.0} ,
{'Question': 'Ile krokietów jest w jednej kostce?', 'Answer': 2.0} ,
{'Question': 'Ile kostek domina jest w pełnym zestawie?', 'Answer': 28.0} ,
{'Question': 'Ile twarzy jest na okładce albumu "Sgt. Pepper\'s Lonely Hearts Club Band"?', 'Answer': 75.0} ,
{'Question': 'Ile twarzy ma bryła dwunastościanu foremnego?', 'Answer': 12.0} ,
{'Question': 'Ile jest Furlongów w Mili?', 'Answer': 8.0} ,
{'Question': 'Ile serc ma dżdżownica?', 'Answer': 10.0} ,
{'Question': 'Ile płotków pokonuje się w 110-metrowym biegu płotkarskim mężczyzn?', 'Answer': 10.0} ,
{'Question': 'Ile płotków jest w biegu na 110 metrów przez płotki mężczyzn?', 'Answer': 10.0} ,
{'Question': 'Ile linii na ekranie mają telewizory w Wielkiej Brytanii?', 'Answer': 625.0} ,
{'Question': 'Ile liter "M" jest w tytule hitu nr 2 zespołu Crash Test Dummies z lat 90.?', 'Answer': 12.0} ,
{'Question': 'Ilu członków liczy zespół "The Pussy Cat Dolls"?', 'Answer': 7.0} ,
{'Question': 'Ilu mężczyzn było w rzymskim legionie?', 'Answer': 6000.0} ,
{'Question': 'Ile części tradycyjnie składa się na koncert?', 'Answer': 3.0} ,
{'Question': 'Ile z dziesięciu najlepszych singli z lat 60-tych było autorstwa Beatlesów?', 'Answer': 5.0} ,
{'Question': 'Ilu pielgrzymów było na pokładzie Mayflower?', 'Answer': 120.0} ,
{'Question': 'Ilu graczy jest w drużynie polo?', 'Answer': 4.0} ,
{'Question': 'Ilu zawodników jest w drużynie piłki siatkowej?', 'Answer': 7.0} ,
{'Question': 'Ile czerwonych baloników miała Nena?', 'Answer': 99.0} ,
{'Question': 'Ile półkwartałów jest w krotochwilach?', 'Answer': 4.0} ,
{'Question': 'Ile rodzeństwa ma Dolly Parton?', 'Answer': 11.0} ,
{'Question': 'Ile boków ma "Enneadecagon"?', 'Answer': 19.0} ,
{'Question': 'Ile sióstr jest w grupie "Sister Sledge"?', 'Answer': 4.0} ,
{'Question': 'Ile piosenek nagrał Elvis Presley ze słowem "Blue" w tytule?', 'Answer': 19.0} ,
{'Question': 'Ile prostych linii znajdziesz na angielskim boisku piłkarskim?', 'Answer': 17.0} ,
{'Question': 'Ile kolejnych tytułów w Wimbledonie zdobył Bjorn Borg?', 'Answer': 5.0} ,
{'Question': 'Ile opowiadań jest w "Opowieściach kanterberyjskich" Chaucera?', 'Answer': 23.0} ,
{'Question': 'Ile zębów ma zdrowy dorosły człowiek?', 'Answer': 32.0} ,
{'Question': 'Ile razy Michael Schumaker wygrał Mistrzostwa Świata Kierowców Formuły 1?', 'Answer': 7.0} ,
{'Question': 'Ile turniejów składa się na Wielkiego Szlema Golfowego?', 'Answer': 4.0} ,
{'Question': 'Ile turniejów składa się na Wielkiego Szlema w golfie?', 'Answer': 4.0} ,
{'Question': 'Ile brytyjskich numerów jeden miała Britney Spears?', 'Answer': 3.0} ,
{'Question': 'Ile numerów 1 w Wielkiej Brytanii mieli łącznie Beatlesi?', 'Answer': 18.0} ,
{'Question': 'Ile tygodni spędziła Abba na listach przebojów w Wielkiej Brytanii w latach 70-tych (106, 140, 181, 241)?', 'Answer': 181.0} ,
{'Question': 'Ile lat minęło między piątym i szóstym numerem 1 Blondies?', 'Answer': 17.0} ,
{'Question': 'Ile klubów było w Premier League w sezonie 1997/8?', 'Answer': 20.0} ,
{'Question': 'Ile prezentów otrzymałbyś, gdybyś otrzymał wszystkie prezenty z piosenki "The 12 Days Of Christmas") Czy jest to 196, 296, 364, 398? ?', 'Answer': 364.0} ,
{'Question': 'Ile jest wart jeden milion w systemie binarnym?', 'Answer': 64.0} ,
{'Question': 'Ile warta jest żółta bila w grze w snookera?', 'Answer': 2.0} ,
{'Question': 'Ile lat miał Elvis Presley, kiedy osiągnął swój pierwszy UK No.1 z "All Shook Up"?', 'Answer': 22.0} ,
{'Question': 'Ile lat miał James Dean, kiedy umarł?', 'Answer': 24.0} ,
{'Question': 'Ile lat miał John F. Kennedy, gdy został zamordowany?', 'Answer': 46.0} ,
{'Question': 'Ile lat miał John Lennon, gdy został zamordowany?', 'Answer': 40.0} ,
{'Question': 'Ile lat miała Margaret Thatcher, gdy objęła funkcję premiera Wielkiej Brytanii w 1979 r.?', 'Answer': 53.0} ,
{'Question': 'Ile lat miał założyciel Playboya, Hugh Hefner, kiedy wypuścił na rynek pierwszą edycję "Playboya"?', 'Answer': 27.0} ,
{'Question': 'Ile lat miał Steve Davis, gdy zdobył swój pierwszy tytuł mistrza świata w snookerze?', 'Answer': 23.0} ,
{'Question': 'Ile lat miała tańcząca królowa według słów piosenki Abby o tej samej nazwie?', 'Answer': 17.0} ,
{'Question': 'Jak szybko porusza się końcówka standardowej kosiarki rotacyjnej? (w km/h)?', 'Answer': 200.0} ,
{'Question': 'Jak długi jest najdłuższy tunel? (w km)?', 'Answer': 169.0} ,
{'Question': 'Jak długo przebywał w więzieniu markiz de Sade za przestępstwa seksualne?', 'Answer': 27.0} ,
{'Question': 'Ilu brytyjskich oficerów zostało wepchniętych przez hinduskie oddziały do czarnej dziury w Kalkucie?', 'Answer': 146.0} ,
{'Question': 'Ile choinek produkuje się rocznie w Nowej Szkocji?', 'Answer': 1.0} ,
{'Question': 'Ile Ziem trzeba by było, aby dorównać rozmiarom Słońca? Ponad 1000, 100,000 czy 1,000,000?', 'Answer': 1000000.0} ,
{'Question': 'Ilu Żydów zostało uratowanych w filmie "Lista Schindlera"?', 'Answer': 1100.0} ,
{'Question': 'Ile filmów z serii Koszmar z ulicy Wiązów powstało w latach 80-tych?', 'Answer': 5.0} ,
{'Question': 'Ile złotych medali olimpijskich zdobył Carl Lewis?', 'Answer': 9.0} ,
{'Question': 'Ile stanów USA graniczy z oceanem?', 'Answer': 23.0} ,
{'Question': 'Ile tytułów w Wimbledonie ma Billie-Jean King?', 'Answer': 20.0} ,
{'Question': 'Ile zwierząt jest używanych do oznaczania lat w chińskim kalendarzu?', 'Answer': 12.0} ,
{'Question': 'Ilu apostołów wybrał Jezus?', 'Answer': 12.0} ,
{'Question': 'Ile arondissements składa się na miasto Paryż?', 'Answer': 20.0} ,
{'Question': 'Ilu astronautów obsadzało każdy lot Apollo?', 'Answer': 3.0} ,
{'Question': 'Ile osi ma osiemnastokołowa ciężarówka?', 'Answer': 5.0} ,
{'Question': 'Ile bil znajduje się na stole bilardowym na początku gry?', 'Answer': 16.0} ,
{'Question': 'Ile bil jest używanych w grze w snookera oprócz bili białej?', 'Answer': 21.0} ,
{'Question': 'Ile bil jest używanych w grze w snookera, wliczając w to bilę białą?', 'Answer': 22.0} ,
{'Question': 'Ile świeczek urodzinowych musieli zdmuchnąć Michael Jackson i Madonna w 1998 roku?', 'Answer': 40.0} ,
{'Question': 'Ile bitów jest w jednej bili?', 'Answer': 4.0} ,
{'Question': 'Ile jest kości w ludzkim ciele?', 'Answer': 206.0} ,
{'Question': 'Ile kości jest w ludzkim ciele?', 'Answer': 206.0} ,
{'Question': 'Ile ksiąg znajduje się w Starym Testamencie Biblii?', 'Answer': 39.0} ,
{'Question': 'Ile przycisków (nie licząc control pada) miał oryginalny kontroler NES?', 'Answer': 4.0} ,
{'Question': 'Ile kalorii jest w szklance wody?', 'Answer': 0.0} ,
{'Question': 'Ile kart jest w paczce tarota?', 'Answer': 78.0} ,
{'Question': 'Ile samochodów może wziąć udział w wyścigu Formuły 1?', 'Answer': 26.0} ,
{'Question': 'Ile gwiazd pojawia się na panelu w każdym odcinku teleturnieju "Blankety Blank"?', 'Answer': 6.0} ,
{'Question': 'Ile komórek umiera w ludzkim ciele w każdej minucie?', 'Answer': 300000000.0} ,
{'Question': "Ile dzieci mieści się w 'american dream'?", 'Answer': 2.5} ,
{'Question': 'Ile dzieci świadomie miał JR Ewing, który mieszkał w "Dallas"?', 'Answer': 3.0} ,
{'Question': 'Ile kolorowych kwadratów ma kostka rubika?', 'Answer': 54.0} ,
{'Question': 'Ile lat z rzędu był w telewizji program Eda Sullivana?', 'Answer': 23.0} ,
{'Question': 'Ile gwiazdozbiorów jest używanych we współczesnej astronomii?', 'Answer': 88.0} ,
{'Question': 'Ilu zawodników wzięło udział w pierwszej nowożytnej olimpiadzie?', 'Answer': 484.0} ,
{'Question': 'Ile państw przystąpiło do Organizacji Narodów Zjednoczonych w momencie jej powstania?', 'Answer': 51.0} ,
{'Question': 'Ile jest dni w roku przestępnym?', 'Answer': 366.0} ,
{'Question': 'Ile dni karaluch może żyć bez wody?', 'Answer': 30.0} ,
{'Question': 'Ile dni trwała Sodoma według Markiza de Sade?', 'Answer': 120.0} ,
{'Question': 'Ile dni trwało przetrzymywanie amerykańskich zakładników w Iranie?', 'Answer': 444.0} ,
{'Question': 'Ile dni było w 1976 roku?', 'Answer': 366.0} ,
{'Question': 'Ile dni było w 1976 roku?', 'Answer': 366.0} ,
{'Question': 'Ile dni upłynie zanim zegar tracący 30 minut dziennie znów pokaże właściwy czas?', 'Answer': 24.0} ,
{'Question': 'Ile stopni mają wszystkie kąty w kwadracie?', 'Answer': 360.0} ,
{'Question': 'Ile stopni ma koło?', 'Answer': 360.0} ,
{'Question': 'Ile wgłębień ma piłeczka golfowa?', 'Answer': 336.0} ,
{'Question': 'Ile wgłębień ma piłeczka golfowa?', 'Answer': 336.0} ,
{'Question': 'Ile krążków ma każdy z graczy na początku w warcabach?', 'Answer': 12.0} ,
{'Question': 'Ile kropek jest na macie do twistera?', 'Answer': 30.0} ,
{'Question': 'Ile kropek jest na parze kostek do gry?', 'Answer': 42.0} ,
{'Question': 'Ile odcinków serialu "Fawlty Towers" zostało nakręconych?', 'Answer': 12.0} ,
{'Question': 'Ile odcinków liczyła oryginalna seria Star Trek?', 'Answer': 75.0} ,
{'Question': 'Ile odcinków miała oryginalna seria Star Trek?', 'Answer': 75.0} ,
{'Question': 'Ile gałek ocznych ma czterojajowa ryba?', 'Answer': 2.0} ,
{'Question': 'Ile ścian ma dwunastościan foremny?', 'Answer': 12.0} ,
{'Question': 'Ile stóp mieści się w mili morskiej?', 'Answer': 6080.0} ,
{'Question': 'Ile stóp jest w mili morskiej?', 'Answer': 6080.0} ,
{'Question': 'Ilu wojowników jest grywalnych w grze Street Fighter II?', 'Answer': 8.0} ,
{'Question': 'Ile pięter ma empire state building?', 'Answer': 102.0} ,
{'Question': 'Ile strun ma stratocaster?', 'Answer': 22.0} ,
{'Question': "Ile masz biegów w 'Pole Position'?", 'Answer': 2.0} ,
{'Question': 'Ile prezentów jest w sumie rozdanych w piosence "The Twelve Days of Christmas"?', 'Answer': 364.0} ,
{'Question': 'Ile otworów potrzeba, aby wypełnić Albert Hall?', 'Answer': 4000.0} ,
{'Question': 'Ile obręczy używa się w grze w krokieta?', 'Answer': 6.0} ,
{'Question': 'Ile godzin dziennie śpi fretka?', 'Answer': 20.0} ,
{'Question': 'Ile godzin dziennie śpi fretka?', 'Answer': 20.0} ,
{'Question': 'Ile godzin jest w tygodniu?', 'Answer': 168.0} ,
{'Question': 'Ile płotków w biegu na 400m przez płotki?', 'Answer': 10.0} ,
{'Question': 'Ile płotków musi przeskoczyć biegacz w biegu na 110 m przez płotki mężczyzn?', 'Answer': 10.0} ,
{'Question': 'Ile centymetrów wysokości mają skóry niedźwiedzi noszone przez strażników w Pałacu Buckingham?', 'Answer': 20.0} ,
{'Question': 'Z ilu wysp składają się Hawaje?', 'Answer': 20.0} ,
{'Question': 'Ilu johnów było papieżem?', 'Answer': 21.0} ,
{'Question': 'Ile karatów ma czyste, niestopowe złoto?', 'Answer': 24.0} ,
{'Question': 'Ile klawiszy jest na standardowym fortepianie koncertowym?', 'Answer': 88.0} ,
{'Question': 'Z ilu kilogramów składa się tona metryczna?', 'Answer': 1000.0} ,
{'Question': 'Z ilu okrążeń składa się wyścig Indianapolis 500?', 'Answer': 200.0} ,
{'Question': 'Ile dużych dziur jest w twojej głowie?', 'Answer': 7.0} ,
{'Question': 'Ile batów otrzymał Jezus?', 'Answer': 39.0} ,
{'Question': 'Ile liter składa się na alfabet kambodżański?', 'Answer': 74.0} ,
{'Question': 'Ile jest liter w alfabecie rzymskim?', 'Answer': 26.0} ,
{'Question': 'Ile wersów jest w sonecie?', 'Answer': 14.0} ,
{'Question': 'Ile maskotek miały Igrzyska Olimpijskie w Sydney?', 'Answer': 3.0} ,
{'Question': 'Ile masztów ma kecz?', 'Answer': 2.0} ,
{'Question': 'Ile osób składa się na Izbę Reprezentantów w USA?', 'Answer': 435.0} ,
{'Question': 'Ilu ludzi stąpało po Księżycu?', 'Answer': 12.0} ,
{'Question': 'Ile mil może przebyć pocisk Pershing?', 'Answer': 400.0} ,
{'Question': 'Ile minut trwa każdy okres gry w hokeja?', 'Answer': 20.0} ,
{'Question': 'Ile miesięcy jest w roku?', 'Answer': 12.0} ,
{'Question': 'Ile mięśni jest w człowieku?', 'Answer': 639.0} ,
{'Question': 'Ile pięciocentówek jest w 2,25$?', 'Answer': 45.0} ,
{'Question': 'Ile gwoździ jest w kuflu?', 'Answer': 4.0} ,
{'Question': 'Ile par żeber jest w męskim szkielecie?', 'Answer': 12.0} ,
{'Question': 'Ile osób mieszkało w domu Brady\'ego w serialu "The Brady Bunch"?', 'Answer': 9.0} ,
{'Question': 'Ile elementów znajduje się w zestawie szachowym?', 'Answer': 32.0} ,
{'Question': 'Ile litrów krwi ma przeciętny człowiek w swoim ciele?', 'Answer': 12.0} ,
{'Question': 'Ile litrów krwi ma przeciętny człowiek w swoim ciele?', 'Answer': 12.0} ,
{'Question': 'Ile sztuk teatralnych jest dziś powszechnie przypisywanych Szekspirowi?', 'Answer': 37.0} ,
{'Question': 'Ile kieszeni znajduje się na standardowym stole do snookera?', 'Answer': 6.0} ,
{'Question': 'Ile punktów ma plansza do gry w backgammon?', 'Answer': 24.0} ,
{'Question': 'Ile punktów jest warta tarcza w łucznictwie plenerowym?', 'Answer': 25.0} ,
{'Question': 'Ile punktów wygrywa mecz w badmintona?', 'Answer': 15.0} ,
{'Question': 'Ile pole position zdobył ayrton senna?', 'Answer': 65.0} ,
{'Question': 'Ile możliwych ruchów początkowych mają białe na początku gry w szachy?', 'Answer': 20.0} ,
{'Question': 'Ile funtów waży młot olimpijski?', 'Answer': 16.0} ,
{'Question': 'Ile zębów ma widelec do obiadu?', 'Answer': 4.0} ,
{'Question': 'Ile płyt musi sprzedać album w Wielkiej Brytanii, aby uzyskać status Platynowej Płyty?', 'Answer': 300000.0} ,
{'Question': 'Ile czerwonych pasków jest na amerykańskiej fladze?', 'Answer': 7.0} ,
{'Question': 'Ile żeber ma człowiek?', 'Answer': 24.0} ,
{'Question': 'Ile pokoi znajduje się w pałacu Buckingham?', 'Answer': 602.0} ,
{'Question': 'Ile mandatów zdobyła Szkocka Partia Narodowa w wyborach parlamentarnych w 2015 roku?', 'Answer': 56.0} ,
{'Question': 'Ile sekund składa się na jeden dzień?', 'Answer': 86400.0} ,
{'Question': 'Z ilu sekund składa się dzień?', 'Answer': 86400.0} ,
{'Question': 'Ile półtonów jest w breve?', 'Answer': 256.0} ,
{'Question': 'Ile półtonów jest w oktawie?', 'Answer': 12.0} ,
{'Question': 'Z ilu senatorów składa się Senat Stanów Zjednoczonych?', 'Answer': 100.0} ,
{'Question': 'Ile kartek papieru jest w ryzach?', 'Answer': 500.0} ,
{'Question': 'Ile boków ma dodekagon?', 'Answer': 12.0} ,
{'Question': 'Ile boków ma płatek śniegu? 6,8,10,12?', 'Answer': 6.0} ,
{'Question': 'Ilu widzów może zmieścić się na Stadionie Strahov (największym na świecie)?', 'Answer': 240000.0} ,
{'Question': 'Ile kolorów spektralnych jest w tęczy?', 'Answer': 27.0} ,
{'Question': 'Ile miejsc jest na kostce do gry?', 'Answer': 21.0} ,
{'Question': 'Ile kwadratów znajduje się na planszy do gry w Shogi (japońskie szachy)?', 'Answer': 81.0} ,
{'Question': 'Ile kwadratów jest na szachownicy?', 'Answer': 64.0} ,
{'Question': 'Ile kwadratów jest na szachownicy?', 'Answer': 64.0} ,
{'Question': 'Ile kwadratów jest na planszy shogi (szachy japońskie)?', 'Answer': 81.0} ,
{'Question': 'Ile ran kłutych miał Juliusz Cezar w chwili śmierci ?', 'Answer': 23.0} ,
{'Question': 'Ile gwiazdek znajduje się na logo studia filmowego paramount?', 'Answer': 22.0} ,
{'Question': 'Ile gwiazd znajduje się na fladze Brazylii?', 'Answer': 23.0} ,
{'Question': "Ile gwiazd składa się na 'Krzyż Południa'?", 'Answer': 5.0} ,
{'Question': 'Ile gwiazd znajduje się na fladze Unii Europejskiej?', 'Answer': 12.0} ,
{'Question': 'Ile stopni jest na szczycie wieży eiffla?', 'Answer': 1007.0} ,
{'Question': 'Ile szwów jest na zwykłej piłce baseballowej?', 'Answer': 108.0} ,
{'Question': 'Ile szwów jest na przepisowej piłce baseballowej?', 'Answer': 108.0} ,
{'Question': 'Ile strun ma harfa?', 'Answer': 47.0} ,
{'Question': 'Ile łyżeczek jest w łyżce stołowej (UK)?', 'Answer': 3.0} ,
{'Question': 'Ile kamieni musi zagrać gracz, aby zaliczyć bingo w Scrabble?', 'Answer': 7.0} ,
{'Question': 'Ile razy Ray Reardon zdobył mistrzostwo świata w snookerze?', 'Answer': 6.0} ,
{'Question': 'Ilu było mędrców?', 'Answer': 3.0} ,
{'Question': 'Ile czarownic jest w jednym przymierzu?', 'Answer': 13.0} ,
{'Question': 'Ile żon miał podobno przywódca mormonów Brigham Young?', 'Answer': 27.0} ,
{'Question': 'Ile lat potrzeba, aby Saturn okrążył Słońce?', 'Answer': 29.0} ,
{'Question': 'Ile lat w roku wiktoriańskim?', 'Answer': 20.0} ,
{'Question': 'Ile lat Nelson Mandela przebywał w więzieniu?', 'Answer': 27.0} ,
{'Question': 'Ile lat upłynęło między powstaniem Magna Carta a amerykańską Deklaracją Niepodległości?', 'Answer': 561.0} ,
{'Question': 'Ile kosztuje Park Place w Monopoly (w dolarach amerykańskich)?', 'Answer': 450.0} ,
{'Question': 'Ile wynosi podatek od luksusu (w dolarach) w grze Monopoly?', 'Answer': 75.0} ,
{'Question': 'Z jaką sumą pieniędzy zaczynasz w grze "Wall Street Kid"?', 'Answer': 500000.0} ,
{'Question': 'Jaką część powierzchni Ziemi pokrywa woda?', 'Answer': 70.0} ,
{'Question': 'Ile lat miał Aleksander Wielki kiedy zmarł ?', 'Answer': 32.0} ,
{'Question': 'Ile lat miał Boris Becker, kiedy wygrał swój pierwszy w karierze turniej singlowy na Wimbledonie?', 'Answer': 17.0} ,
{'Question': 'Ile lat miał John F. Kennedy, kiedy został prezydentem?', 'Answer': 43.0} ,
{'Question': 'Ile lat miała Sarah, kiedy urodziła dziecko?', 'Answer': 90.0} ,
{'Question': 'Ile lat miał Stanley Matthews, gdy odszedł na emeryturę w 1965 roku?', 'Answer': 50.0} ,
{'Question': 'Ile lat miała Shirley Temple, gdy nakręciła swój ostatni film?', 'Answer': 21.0} ,
{'Question': 'Ile lat miał najstarszy człowiek na świecie?', 'Answer': 141.0} ,
{'Question': 'Jak wysokie są skóry niedźwiedzi noszone przez strażników w pałacu Buckingham?', 'Answer': 20.0} ,
{'Question': 'Ile tysięcy osób oddało życie podczas wojny domowej w USA?', 'Answer': 30.0} ,
{'Question': 'W którym roku odbył się strajk generalny w Wielkiej Brytanii?', 'Answer': 1926.0} ,
{'Question': 'W którym roku założono firmę IBM?', 'Answer': 1896.0} ,
{'Question': 'Jaki wynik uzyskałbyś, gdybyś miał czerwone, czarne i różowe karty w snookerze?', 'Answer': 15.0} ,
{'Question': 'Gdybyś wziął liczbę milion i zamienił ją na postać binarną, ile by ona wynosiła?', 'Answer': 64.0} ,
{'Question': 'Gdyby temperatura ciała wynosiła 86 stopni, ile lat żyłby człowiek?', 'Answer': 200.0} ,
{'Question': 'Jeżeli w Seattle w stanie Waszyngton jest godzina 16:00, to która jest godzina w Portland w stanie Oregon?', 'Answer': 4.0} ,
{'Question': 'Wielbłądy w niewoli, jeśli są dobrze traktowane, mogą dożyć wieku __________?', 'Answer': 50.0} ,
{'Question': 'Jeśli policzysz od 1 do 100, na ile siódemek natrafisz?', 'Answer': 20.0} ,
{'Question': 'W filmie "Running Scared" ile pieniędzy bohater Billy\'ego Crystala odziedziczył po swojej zmarłej ciotce Rose?', 'Answer': 50000.0} ,
{'Question': 'W grze "Pac-Man" na Atari 2600, ile punktów była warta każda kulka?', 'Answer': 1.0} ,
{'Question': 'W 1864 roku, kto został zmasakrowany w obozie Sand Creek w Kolorado?', 'Answer': 300.0} ,
{'Question': 'W 1964 roku umiera Douglas MacArthur, amerykański generał (teatr Pacyfiku - II wojna światowa).?', 'Answer': 84.0} ,
{'Question': 'W 1971 r. Intel wydał pierwszy na świecie mikroprocesor jednoukładowy, pod jakim numerem był on znany?', 'Answer': 4004.0} ,
{'Question': 'W 1975 roku zmarł w wieku lat chiński przywódca nacjonalistyczny Chiang Kai-Shek?', 'Answer': 87.0} ,
{'Question': 'W 1976 roku umiera Howard Hughes, ekskluzywny miliarder.?', 'Answer': 72.0} ,
{'Question': 'W 1986 roku, jaka była maksymalna pojemność paliwa (w litrach) narzucona w wyścigach Formuły 1?', 'Answer': 195.0} ,
{'Question': 'W 1990 roku w meczu testowym przeciwko Indiom Graham Gooch zdobył potrójnego Nelsona. Ile biegów zdobył?', 'Answer': 333.0} ,
{'Question': 'W grze w snookera, jeśli osiągnąłeś perfekcyjne 147 uderzeń, ile razy w sumie miałbyś czarną bilę?', 'Answer': 16.0} ,
{'Question': 'Ile punktów zdobyłbyś za wbicie czarnej bili w doskonałym brejku 147?', 'Answer': 112.0} ,
{'Question': 'W Animal House, jaka była średnia ocen Bluto?', 'Answer': 0.0} ,
{'Question': 'W Australian Rules Football ilu zawodników może być jednocześnie na boisku w drużynie?', 'Answer': 18.0} ,
{'Question': 'W Bingo, do czego służą 2 Grube Damy?', 'Answer': 88.0} ,
{'Question': 'W Wielkiej Brytanii lotnisko Stanstead zostało oficjalnie otwarte w którym roku?', 'Answer': 1991.0} ,
{'Question': 'W Wielkiej Brytanii w którym roku sufrażystka rzuciła się pod królewskiego konia?', 'Answer': 1913.0} ,
{'Question': 'W Wielkiej Brytanii w którym roku otwarto most kolejowy Forth?', 'Answer': 1890.0} ,
{'Question': 'W "A Christmas Carol" Charlesa Dickensa, ile różnych duchów odwiedziło Scrooge\'a?', 'Answer': 4.0} ,
{'Question': 'W rzutki z jakiego numeru poniżej 100, nie jest możliwe, aby zakończyć z 2 rzutki?', 'Answer': 99.0} ,
{'Question': 'W Anglii w którym roku była katastrofa powodziowa w Lynmouth?', 'Answer': 1952.0} ,
{'Question': 'W miarach imperialnych, ile funtów jest w jednej setnej wagi?', 'Answer': 112.0} ,
{'Question': 'W miarach imperialnych, ile jardów kwadratowych są w łańcuchu kwadratowym?', 'Answer': 484.0} ,
{'Question': 'W czerwcu którego roku został podpisany traktat kończący I wojnę światową?', 'Answer': 1919.0} ,
{'Question': 'Kiedy w Londynie zapalił się teatr Globe?', 'Answer': 1613.0} ,
{'Question': 'Kiedy w Londynie odbył się pierwszy mecz krykieta w Lords?', 'Answer': 1814.0} ,
{'Question': 'Jaki jest koszt wyjścia z więzienia w grze Monopoly?', 'Answer': 50.0} ,
{'Question': 'W grze Monopoly, jaki jest koszt zakupu Electric Company?', 'Answer': 150.0} ,
{'Question': 'W grze Monopoly, jaki jest koszt kupna New York Avenue?', 'Answer': 200.0} ,
{'Question': 'W grze Monopoly, jaki jest koszt kupna Oriental Avenue?', 'Answer': 100.0} ,
{'Question': 'W Monopoly, Jaki jest koszt kupna Vermont Avenue?', 'Answer': 100.0} ,
{'Question': "Jaki był średni wiek żołnierza walczącego podczas wojny w Wietnamie w przeboju Paula Hardcastle'a?", 'Answer': 19.0} ,
{'Question': 'W snookerze ile warta jest bila (czerwona czarna czerwona zielona czerwona)?', 'Answer': 13.0} ,
{'Question': 'W Squashu każda gra jest rozgrywana do momentu, aż gracz zdobędzie ile punktów?', 'Answer': 15.0} ,
{'Question': 'W Super Mario Bros. 2, ile dodatkowych żyć otrzymasz za zakręcenie trzema siódemkami na automacie?', 'Answer': 10.0} ,
{'Question': 'W którym roku Blackburn Rovers po raz ostatni wygrali finał Pucharu Anglii?', 'Answer': 1928.0} ,
{'Question': 'W którym roku kapitan Cook dotarł do Nowej Zelandii?', 'Answer': 1769.0} ,
{'Question': 'W którym roku Wielka Brytania przejęła kontrolę nad Hong Hong?', 'Answer': 1842.0} ,
{'Question': 'W którym roku Indie uzyskały niepodległość od brytyjskich rządów kolonialnych?', 'Answer': 1947.0} ,
{'Question': 'W którym roku Indie uzyskały niepodległość oznaczającą początek dekolonizacji?', 'Answer': 1947.0} ,
{'Question': 'W którym roku MTV po raz pierwszy weszło na antenę A) 1979, B) 1980, C) 1981, D) 1982?', 'Answer': 1981.0} ,
{'Question': 'W którym roku Madonna poślubiła Seana Penna?', 'Answer': 1985.0} ,
{'Question': 'W którym roku Michaił Gorbaczow został przywódcą Związku Radzieckiego?', 'Answer': 1985.0} ,
{'Question': 'W którym roku Neil Armstrong po raz pierwszy postawił stopę na Księżycu?', 'Answer': 1969.0} ,
{'Question': 'W którym roku Robbie Williams odszedł z Take That?', 'Answer': 1995.0} ,
{'Question': 'W którym roku rosyjski programista komputerowy "Alexi Pachitnov" zaprojektował i zaprogramował grę Tetris?', 'Answer': 1985.0} ,
{'Question': 'W którym roku zakończyła się amerykańska wojna secesyjna?', 'Answer': 1865.0} ,
{'Question': 'W którym roku rozpoczęła się rewolucja francuska?', 'Answer': 1789.0} ,
{'Question': 'W którym roku wybuchł wielki pożar Londynu?', 'Answer': 1666.0} ,
{'Question': 'W którym roku rozpoczęła się hiszpańska wojna domowa?', 'Answer': 1936.0} ,
{'Question': 'W którym roku rozpoczęła się wojna w Wietnamie?', 'Answer': 1954.0} ,
{'Question': 'W którym roku zespół Wet Wet Wet Wet z utworem "Love Is All Around" przez 15 tygodni utrzymywał się na szczycie brytyjskiej listy przebojów?', 'Answer': 1994.0} ,
{'Question': 'W którym roku rozpoczęła się I wojna światowa?', 'Answer': 1914.0} ,
{'Question': 'W którym roku zakończyła się I wojna światowa?', 'Answer': 1918.0} ,
{'Question': 'W którym roku Abraham Lincoln został zamordowany?', 'Answer': 1865.0} ,
{'Question': 'W którym roku utwór "Do They Know Its Christmas" zespołu Aids był singlem nr 1 w Wielkiej Brytanii?', 'Answer': 1984.0} ,
{'Question': 'W którym roku urodziła się królowa Elżbieta I?', 'Answer': 1533.0} ,
{'Question': 'W którym roku został zamordowany Robert Kennedy? (2 punkty za trafienie, 1 punkt za rok, tak czy inaczej)?', 'Answer': 1968.0} ,
{'Question': 'W którym roku wzniesiono mur berliński?', 'Answer': 1916.0} ,
{'Question': 'W którym roku powstała Republika Chińska?', 'Answer': 1911.0} ,
{'Question': 'W którym roku odbyła się pierwsza przeprawa przez Atlantyk napędzana śmigłem?', 'Answer': 1845.0} ,
{'Question': 'W którym roku uchwalono francuską Deklarację Praw Człowieka (wolność, równość, braterstwo)?', 'Answer': 1789.0} ,
{'Question': 'W którym roku odbył się strajk generalny?', 'Answer': 1926.0} ,
{'Question': 'W którym roku w Wielkiej Brytanii wprowadzono emeryturę?', 'Answer': 1908.0} ,
{'Question': 'W którym roku piosenka "Hello Goodbye" była numerem 1?', 'Answer': 1967.0} ,
{'Question': 'W którym roku odkryto grób Tutanchamona?', 'Answer': 1922.0} ,
{'Question': 'W którym roku powstała Organizacja Narodów Zjednoczonych?', 'Answer': 1945.0} ,
{'Question': 'W którym roku Stock, Aitken & Waterman przeprawili się promem przez Mersey?', 'Answer': 1989.0} ,
{'Question': 'W którym roku komórki tkanek zostały po raz pierwszy wyhodowane poza organizmem przez naszego biologa Rossa Harrisona?', 'Answer': 1905.0} ,
{'Question': 'W którym roku Steve Redgrave zdobył swój pierwszy złoty medal na Olimpiadzie?', 'Answer': 1984.0} ,
{'Question': 'W którym roku (come on you reds) singiel Man Utd był nr 1?', 'Answer': 1994.0} ,
{'Question': 'W którym roku utwór "Country House" był numerem jeden dla Blur?', 'Answer': 1995.0} ,
{'Question': 'W którym roku "Wooden Heart" i "Surrender" osiągnęły nr 1 dla Elvisa?', 'Answer': 1961.0} ,
{'Question': 'W którym roku & The Pacemakers osiągnęli trzy nr 1?', 'Answer': 1963.0} ,
{'Question': 'W którym roku radziecki kosmonauta wykonał pierwszy spacer kosmiczny?', 'Answer': 1965.0} ,
{'Question': 'W którym roku Abba wygrała Konkurs Piosenki Eurowizji?', 'Answer': 1974.0} ,
{'Question': 'W którym roku rozwiedli się Benny i Frida z Abby?', 'Answer': 1981.0} ,
{'Question': 'W którym roku Albatros znalazł się na szczycie listy przebojów Fleetwood Mac?', 'Answer': 1968.0} ,
{'Question': 'W którym roku Bianca została panią Mick Jagger (1970, 1972, 1974, 1976)?', 'Answer': 1970.0} ,
{'Question': 'W którym roku Bucks Fizz wygrali konkurs piosenki Eurowizji?', 'Answer': 1981.0} ,
{'Question': 'W którym roku Daley Thompson został sportową osobowością roku BBC?', 'Answer': 1982.0} ,
{'Question': 'W którym roku hymn disco Donny Summers "I Feel Love" stał się numerem 1?', 'Answer': 1977.0} ,
{'Question': 'W którym roku Eddie the Eagle Edwards zdobył sławę na Zimowych Igrzyskach Olimpijskich?', 'Answer': 1988.0} ,
{'Question': 'W którym roku zmarła Janis Joplin?', 'Answer': 1970.0} ,
{'Question': 'W którym roku Kraftwerk osiągnęli swój pierwszy UK No.1?', 'Answer': 1982.0} ,
{'Question': 'W którym roku Micheal Jackson znalazł się na szczycie listy przebojów z piosenką "Black Or White"?', 'Answer': 1991.0} ,
{'Question': 'W którym roku Phil Collins dołączył do Genesis?', 'Answer': 1970.0} ,
{'Question': 'W którym roku Procol Harum otworzyli Puszkę Pandory?', 'Answer': 1975.0} ,
{'Question': 'W którym roku Rod Stewart wydał "Baby Jane", 1983, 1984, 1986?', 'Answer': 1983.0} ,
{'Question': 'W którym roku Sting wydał Fields Of Gold?', 'Answer': 1993.0} ,
{'Question': 'W którym roku pływanie synchroniczne zadebiutowało na olimpiadzie?', 'Answer': 1984.0} ,
{'Question': 'W którym roku zespół zagrał darmowy koncert w londyńskim Hyde Parku?', 'Answer': 1969.0} ,
{'Question': 'W którym roku odbyła się bitwa pod Hastings?', 'Answer': 1066.0} ,
{'Question': 'W którym roku The Bay City Rollers mieli 2 single na pierwszym miejscu?', 'Answer': 1975.0} ,
{'Question': 'W którym roku The Beach Boys wydali "Good Vibrations" i "Sloop John B"?', 'Answer': 1966.0} ,
{'Question': 'W którym roku rozpoczął się konflikt na Falklandach?', 'Answer': 1982.0} ,
{'Question': 'W którym roku tankowiec Torrey Canyon osiadł na mieliźnie w pobliżu Lands End, powodując poważną katastrofę ekologiczną?', 'Answer': 1967.0} ,
{'Question': 'W którym roku zespół The Stranglers osiągnął trzy przeboje w pierwszej dziesiątce?', 'Answer': 1977.0} ,
{'Question': 'W którym roku po raz pierwszy pojawił się Volkswagen Beetle?', 'Answer': 1945.0} ,
{'Question': 'W którym roku Torville & Dean zdobyli złoto olimpijskie dzięki swojemu Bolero?', 'Answer': 1984.0} ,
{'Question': 'W którym roku Bobby Brown miał więcej tygodni na UK Chart niż inni artyści?', 'Answer': 1989.0} ,
{'Question': 'W którym roku utwór "Crying In The Chapel" stał się hitem nr 1 dla Elvisa?', 'Answer': 1965.0} ,
{'Question': 'W którym roku Cilla szukała "Anyone Who Had A Heart" 1961, 1964, 1967?', 'Answer': 1964.0} ,
{'Question': 'W którym roku Culture Clubs Karma Chameleon stało się hitem?', 'Answer': 1983.0} ,
{'Question': "W którym roku Joanna d'Arc została spalona na stosie?", 'Answer': 1431.0} ,
{'Question': 'W którym roku zamordowano Johna Lennona?', 'Answer': 1980.0} ,
{'Question': 'W którym roku John Lennon został zastrzelony w Nowym Jorku?', 'Answer': 1980.0} ,
{'Question': 'W którym roku Pan Blobby był świątecznym numerem jeden w Wielkiej Brytanii?', 'Answer': 1993.0} ,
{'Question': 'W którym roku Roy Orbison był jedynym amerykańskim artystą solowym, który był numerem 1 w Wielkiej Brytanii?', 'Answer': 1964.0} ,
{'Question': 'W którym roku wydano Gorączkę sobotniej nocy?', 'Answer': 1978.0} ,
{'Question': 'W którym roku porwano Szergara?', 'Answer': 1983.0} ,
{'Question': 'W którym roku odbyła się bitwa pod Trafalgarem?', 'Answer': 1805.0} ,
{'Question': 'W którym roku zbudowano mur berliński?', 'Answer': 1961.0} ,
{'Question': 'W którym roku Boeing 747 wszedł do regularnej służby?', 'Answer': 1970.0} ,
{'Question': 'W którym roku zniesiono prawo pozwalające na palenie czarownic?', 'Answer': 1736.0} ,
{'Question': 'W którym roku wydano po raz pierwszy YMCA 1975, 1977 lub 1979?', 'Answer': 1979.0} ,
{'Question': 'W którym roku na listach przebojów znalazły się następujące utwory: "Ghostbusters" Raya Parkera Juniora, "Jump" Van Halen i "Smalltown Boy" Bronski Beat?', 'Answer': 1984.0} ,
{'Question': 'W którym roku na brytyjskich listach przebojów znalazły się następujące utwory: "Come As You Are" Nirvany, "The Crying Game" Boy George\'a i "Rhythm Is A Dancer" Snap?', 'Answer': 1992.0} ,
{'Question': 'W którym roku były następujące przeboje na wszystkich listach przebojów w Wielkiej Brytanii: "Solsbury Hill" Petera Gabriela, "Silver Lady" Davida Soula i "Pearl\'s A Singer" Elkie Brooksa?', 'Answer': 1977.0} ,
{'Question': 'In Which Year Were The Following All UK Chart Hits: "To Cut A Long Story Short" By Spandau Ballet, "Pulling Mussels From The Shell" By Squeeze And "Perfect Cousin" By The Undertones?', 'Answer': 1980.0} ,
{'Question': 'W którym roku The Housemartins mieli Happy Hour?', 'Answer': 1986.0} ,
{'Question': 'W którym roku John Lennon powiedział nam Happy Xmas (War Is Over)?', 'Answer': 1972.0} ,
{'Question': 'W którym roku Beatlesi wydali "Get Back" Czy był to rok 1967, 1968, 1969?', 'Answer': 1969.0} ,
{'Question': 'W którym roku wydano po raz drugi singiel Band Aid "Feed The World"?', 'Answer': 1989.0} ,
{'Question': 'W maksymalnym brejku snookerowym 147, ile punktów jest zdobywanych na samej czarnej bili?', 'Answer': 112.0} ,
{'Question': 'Ile razy w okresie 400 lat dzień 1 stycznia wypada w niedzielę?', 'Answer': 58.0} ,
{'Question': "W którym mniej więcej roku urodziła się Joanna d'Arc?", 'Answer': 1412.0} ,
{'Question': 'W futbolu zawodowym okres "nagłej śmierci" trwa ile minut?', 'Answer': 15.0} ,
{'Question': 'W snookerze, ile punktów gromadzi się za perfekcyjny break?', 'Answer': 147.0} ,
{'Question': 'W standardowym filmie kinowym ile klatek jest wyświetlanych w każdej sekundzie?', 'Answer': 24.0} ,
{'Question': 'Ile punktów składa się na perfekcyjną grę w kręgle w tenisa stołowego?', 'Answer': 300.0} ,
{'Question': 'W filmie "Dwanaście dni świąt" ile przedmiotów w sumie wysyła "moja prawdziwa miłość"?', 'Answer': 78.0} ,
{'Question': 'W "Twelve days of christmas", ile przedmiotów w sumie wysyła "moja prawdziwa miłość"?', 'Answer': 78.0} ,
{'Question': "Ile godzin dzieli Gene'a Pitneya od Tulsy?", 'Answer': 24.0} ,
{'Question': 'W USA 911, w Wielkiej Brytanii 999, co w Australii?', 'Answer': 0.0} ,
{'Question': 'W Stanach Zjednoczonych na przełomie wieków było ile stanów?', 'Answer': 45.0} ,
{'Question': 'W którym roku Bob Budowniczy miał brytyjski przebój nr 1 na Boże Narodzenie z utworem "Can We Fix It"?', 'Answer': 2000.0} ,
{'Question': 'W którym roku wygasła dzierżawa Hongkongu przez Anglię?', 'Answer': 1997.0} ,
{'Question': 'W którym roku Lord Lucan popadł w zapomnienie?', 'Answer': 1974.0} ,
{'Question': 'W którym roku po raz pierwszy pojawiły się Peanuts i Beetle Bailey?', 'Answer': 1950.0} ,
{'Question': 'W którym roku człowiek po raz pierwszy postawił stopę na Księżycu?', 'Answer': 1969.0} ,
{'Question': 'W którym roku zespół Pretenders wydał swój pierwszy LP?', 'Answer': 1980.0} ,
{'Question': 'W którym roku skończyła się dzienna racja rumu w Królewskiej Marynarce Wojennej?', 'Answer': 1970.0} ,
{'Question': 'W którym roku II wojny światowej Rosja wypowiedziała wojnę Japonii?', 'Answer': 1945.0} ,
{'Question': 'W którym roku ukazał się film "Dirty Dancing"?', 'Answer': 1987.0} ,
{'Question': 'W którym roku utwór "Do They Know It\'s Christmas" zespołu Band-Aid był najlepiej sprzedającą się płytą na brytyjskiej liście przebojów świątecznych?', 'Answer': 1984.0} ,
{'Question': 'W którym roku urodził się książę Harry?', 'Answer': 1984.0} ,
{'Question': 'W którym roku została wyprodukowana pierwsza kartka świąteczna?', 'Answer': 1846.0} ,
{'Question': 'W którym roku ukończono pierwsze angielskie tłumaczenie Biblii?', 'Answer': 1388.0} ,
{'Question': 'W którym roku odbyły się pierwsze Mistrzostwa Świata w Snookerze w Crucible Theatre w Sheffield?', 'Answer': 1977.0} ,
{'Question': 'Na których igrzyskach Mark Spitz ustanowił nowy rekord olimpijski zdobywając siedem złotych medali?', 'Answer': 1972.0} ,
{'Question': 'Na której Olimpiadzie Mark Spitz zdobył siedem złotych medali?', 'Answer': 1972.0} ,
{'Question': 'W którym roku George McCrae wydał swój przebój nr 1 "Rock Your Baby"?', 'Answer': 1974.0} ,
{'Question': 'W której książce jest "Wielki Brat?', 'Answer': 1984.0} ,
{'Question': 'W której powieści Wielki Brat mógłby cię obserwować?', 'Answer': 1984.0} ,
{'Question': 'W którym roku Eddie the Eagle Edwards reprezentował Anglię?', 'Answer': 1988.0} ,
{'Question': 'W którym roku królowa wygłosiła swój niesławny program świąteczny "Annus Horriblis"?', 'Answer': 1992.0} ,
{'Question': 'W którym roku zatonął Titanic?', 'Answer': 1912.0} ,
{'Question': 'W którym roku rozpoczęto burzenie muru berlińskiego?', 'Answer': 1989.0} ,
{'Question': 'W którym roku panowało trzech niemieckich cesarzy?', 'Answer': 1888.0} ,
{'Question': 'W którym roku zbudowano Ascot?', 'Answer': 1711.0} ,
{'Question': 'W którym roku zbudowano mur berliński?', 'Answer': 1961.0} ,
{'Question': 'W którym roku zniesiono brytyjską licencję dla psów?', 'Answer': 1987.0} ,
{'Question': 'W którym roku rozpoczęło się Lato Miłości?', 'Answer': 1967.0} ,
{'Question': 'W którym roku odbył się pierwszy finał Pucharu Anglii na Wembley?', 'Answer': 1923.0} ,
{'Question': 'W którym roku Londyn będzie gospodarzem Igrzysk Olimpijskich?', 'Answer': 2012.0} ,
{'Question': 'W którym roku powstał w Niemczech zespół disco Boney M?', 'Answer': 1976.0} ,
{'Question': 'W którym roku Indie uzyskały niepodległość?', 'Answer': 1947.0} ,
{'Question': 'Na ile miesięcy podzielony był kalendarz juliański, wprowadzony w 46 r. p.n.e. przez Juliusza Cezara?', 'Answer': 12.0} ,
{'Question': 'W którym roku Jack Nicholson i Jessica Lange wystąpili w remake\'u filmu "Listonosz zawsze dzwoni dwa razy"?', 'Answer': 1981.0} ,
{'Question': 'W którym roku James I wstąpił na tron Anglii?', 'Answer': 1603.0} ,
{'Question': 'Ile lat miała Joan Collins, kiedy pozowała półnago dla "Playboya" w 1983 roku?', 'Answer': 50.0} ,
{'Question': 'W którym roku Jodie Foster wyreżyserowała film "Little Man Tate"?', 'Answer': 1991.0} ,
{'Question': 'W którym roku Joe Louis został mistrzem świata?', 'Answer': 1937.0} ,
{'Question': 'John Garfield i Lana Turner wystąpili w filmie "Listonosz zawsze dzwoni dwa razy", w którym roku został on wydany?', 'Answer': 1945.0} ,
{'Question': 'Joseph Adams był pastorem w Newington przez ile lat?', 'Answer': 68.0} ,
{'Question': 'Jr ile utworów zabrzmiało z szafy grającej Wurlitzer model 1100 z 1948 roku?', 'Answer': 24.0} ,
{'Question': 'Lemniscate to prawidłowa nazwa jakiego symbolu?', 'Answer': 'nieskończoność'} ,
{'Question': 'Leonardo Michelangelo Raphael Ile kwadratów znajduje się na planszy do gry w Shogi (japońskie szachy)?', 'Answer': 81.0} ,
{'Question': 'Mary Robinson została prezydentem Irlandii w którym roku?', 'Answer': 1990.0} ,
{'Question': 'Melony składają się w przybliżeniu z jakiego procentu wody?', 'Answer': 90.0} ,
{'Question': 'Messyna została zniszczona przez trzęsienie ziemi w którym roku?', 'Answer': 1908.0} ,
{'Question': 'W którym roku Michael Jackson zaśpiewał piosenkę "Ben"?', 'Answer': 1972.0} ,
{'Question': 'W którym roku ukazał się utwór "Moving On Up" zespołu M-people?', 'Answer': 1993.0} ,
{'Question': 'Mungo Scott przepłynął rzekę Niger w którym roku?', 'Answer': 1795.0} ,
{'Question': 'W którym roku w Monachium odbyły się Igrzyska Olimpijskie?', 'Answer': 1972.0} ,
{'Question': 'Nadine Gordimer otrzymała literacką Nagrodę Nobla w którym roku?', 'Answer': 1991.0} ,
{'Question': 'Podaj rok śmierci Hotelu California, Elvisa Presleya, narodzin Ronana Keatinga?', 'Answer': 1977.0} ,
{'Question': 'Podaj rok, w którym zastrzelono Johna Lennona, wydano "Crying" Dona Mcleana i film "Blues Bros".?', 'Answer': 1980.0} ,
{'Question': 'Podaj rok, w którym Relax osiągnął nr 1 w Wielkiej Brytanii, "This Is Spinal Tap", urodzony w USA?', 'Answer': 1984.0} ,
{'Question': 'Podaj rok: "Wichrowe Wzgórza", Grease (film), Keith Moon umiera z przedawkowania?', 'Answer': 1978.0} ,
{'Question': 'Nat King Cole zmarł w którym roku?', 'Answer': 1965.0} ,
{'Question': 'Stopnie marynarki: gwiazdy, które ma "commodore?', 'Answer': 1.0} ,
{'Question': 'Ncaa: w którym roku po raz pierwszy przyznano pamiątkowe trofeum heismana?', 'Answer': 1935.0} ,
{'Question': 'New jersey ma łyżkę z ponad _________ łyżkami z każdego stanu i prawie każdego kraju?', 'Answer': 5400.0} ,
{'Question': 'Liczba konwencji Beatlesów odbywających się każdego roku na całym świecie?', 'Answer': 15.0} ,
{'Question': 'Liczba fanzinów Beatlesów wydawanych obecnie na całym świecie?', 'Answer': 44.0} ,
{'Question': 'Liczba piosenek Beatlesów z imieniem kobiety w tytule?', 'Answer': 18.0} ,
{'Question': 'Liczba zespołów będących hołdem dla Beatlesów, które obecnie występują?', 'Answer': 44.0} ,
{'Question': "Liczba stron internetowych związanych z Beatlesami wymienionych na stronie Dave'a Habera?", 'Answer': 52.0} ,
{'Question': 'Liczba artystów muzycznych, którzy wykonali cover "Yesterday?', 'Answer': 2961.0} ,
{'Question': 'Liczba permutacji zespołu Wings?', 'Answer': 6.0} ,
{'Question': 'Liczba punktów straconych za zdrapanie niebieskiej bili w snookerze?', 'Answer': 5.0} ,
{'Question': 'Liczba kromek poświęconych na nakręcenie reklamy Ringo w Pizza Hut?', 'Answer': 12.0} ,
{'Question': 'Liczba solowych albumów poszczególnych Beatlesów?', 'Answer': 71.0} ,
{'Question': 'Liczba tygodni, które albumy Beatlesów spędziły na pozycji nr 1?', 'Answer': 147.0} ,
{'Question': 'Liczba lat, przez które Beatlemania koncertowała w Stanach Zjednoczonych?', 'Answer': 5.0} ,
{'Question': 'Ilu brytyjskich oficerów zostało wepchniętych przez wojska indyjskie do czarnej dziury w Kalkucie?', 'Answer': 146.0} ,
{'Question': 'Old Moore\'s Almanac" został założony w którym roku?', 'Answer': 1699.0} ,
{'Question': 'W Przyjaciołach, co Phoebe obiecała dać Chandlerowi, jeśli nigdy więcej nie będzie palić?', 'Answer': 7000.0} ,
{'Question': 'Na tarczy do rzutek, jaka liczba jest na górze?', 'Answer': 20.0} ,
{'Question': 'Na zegarze analogowym, która cyfra wskazuje 4?', 'Answer': 10.0} ,
{'Question': 'W nocnym sądzie, jakie było IQ Byka?', 'Answer': 181.0} ,
{'Question': 'W dniu 1 lipca którego roku brytyjska kolonia Hongkong została zwrócona Chinom?', 'Answer': 1997.0} ,
{'Question': 'Ile stopni w skali Fahrenheita jest między temperaturą zamarzania a temperaturą wrzenia?', 'Answer': 180.0} ,
{'Question': 'W którym dniu upadł "Mur"?', 'Answer': 1989.0} ,
{'Question': 'W jakim dniu upadł "Mur"?', 'Answer': 1989.0} ,
{'Question': 'W który dzień Bożego Narodzenia wojska angielskie i niemieckie grały w piłkę nożną?', 'Answer': 1914.0} ,
{'Question': 'W którym roku jeden z okrętów Ferdynanda Magellena dokonał pierwszego opłynięcia świata?', 'Answer': 1522.0} ,
{'Question': 'W pierwszym roku działalności Disney World na Florydzie odwiedziło zaledwie 10 000 osób. Z czasem jednak frekwencja wzrosła do ponad _________ osób na godzinę.?', 'Answer': 10000.0} ,
{'Question': 'Ile okrążeń ma wyścig Indianapolis 500?', 'Answer': 200.0} ,
{'Question': 'Na jakim dystansie rozgrywany jest wyścig konny Melbourne Cup (w metrach)?', 'Answer': 3200.0} ,
{'Question': 'Papierowa Koronka" powiedziała Billy\'emu, żeby nie był bohaterem, w którym roku?', 'Answer': 1974.0} ,
{'Question': 'Pasteur opracował szczepionkę na wściekliznę w którym roku?', 'Answer': 1885.0} ,
{'Question': 'Paul Keating został wybrany premierem Australii w którym roku?', 'Answer': 1991.0} ,
{'Question': 'W którym roku urodził się Peter Lorre?', 'Answer': 1904.0} ,
{'Question': 'W którym roku Fineasz Barnum otworzył swój cyrk?', 'Answer': 1871.0} ,
{'Question': 'W którym roku po raz pierwszy wprowadzono do obiegu znaczki pocztowe w Wielkiej Brytanii?', 'Answer': 1840.0} ,
{'Question': 'Książę miał zamiar imprezować, jakby to był który rok?', 'Answer': 1999.0} ,
{'Question': 'Królowa Wiktoria urodziła się w tym roku.?', 'Answer': 1819.0} ,
{'Question': 'Robin Hood: Książę złodziei został wydany w którym roku?', 'Answer': 1992.0} ,
{'Question': 'Roe wykonał pierwszy lot do Wielkiej Brytanii brytyjskim samolotem w którym roku?', 'Answer': 1909.0} ,
{'Question': 'Roosevelt odniósł zwycięstwo nad Hooverem w którym roku?', 'Answer': 1932.0} ,
{'Question': 'Roy Chapman stał się pierwszą ofiarą śmiertelną w baseballu w którym roku?', 'Answer': 1920.0} ,
{'Question': 'W którym roku odbyła się premiera filmu Rudolpha Valentina?', 'Answer': 1921.0} ,
{'Question': 'Salvador Allende były prezydent Chile został zamordowany w którym roku?', 'Answer': 1973.0} ,
{'Question': 'W którym roku ukazał się słownik Samuela Johnsona?', 'Answer': 1755.0} ,
{'Question': 'Siedemnaście tysięcy ilu wielbłądów niosło 117 000 tomów biblioteki Abdula Kassema Ismaela?', 'Answer': 400.0} ,
{'Question': 'W którym roku wprowadzono do piłki nożnej ochraniacze?', 'Answer': 1839.0} ,
{'Question': 'Smetana w jakiej powieści ukazuje Winstona Smitha żyjącego w Oceanii i walczącego z podwójną mową i policją myśli?', 'Answer': 1984.0} ,
{'Question': 'W którym roku w Chicago zaczęto grać w softball?', 'Answer': 1888.0} ,
{'Question': 'Rozwiąż to: 10*3+2?', 'Answer': 32.0} ,
{'Question': 'W którym roku wyprodukowano taśmę klejącą?', 'Answer': 1928.0} ,
{'Question': 'Telewizory Ben Casey zaczął od Człowiek Kobieta Narodziny Śmierć i co?', 'Answer': 'nieskończoność'} ,
{'Question': 'Ted Hughes laureat poezji zmarł w którym roku?', 'Answer': 1998.0} ,
{'Question': 'Olimpiada "Rydwany ognia" odbyła się w którym roku?', 'Answer': 1924.0} ,
{'Question': 'Ile dni trwał strajk piłkarski w 1982 roku?', 'Answer': 57.0} ,
{'Question': 'Pierwsze amerykańskie święto federalne ku czci Martina Luthera Kinga jr. odbyło się w którym roku?', 'Answer': 1986.0} ,
{'Question': 'W którym roku wprowadzono pierwsze amerykańskie prawo o płacy minimalnej?', 'Answer': 1938.0} ,
{'Question': 'W którym roku w chicagowskim Lincoln Park Zoo urodził się pierwszy bawół w historii, który przyszedł na świat w niewoli?', 'Answer': 1884.0} ,
{'Question': 'W którym roku wszedł do sprzedaży pierwszy komputer osobisty?', 'Answer': 1977.0} ,
{'Question': 'Zespół The 3 Degrees nagrał płytę "Ta ke Good Care Of Yourself" w jakim roku 1972,1973,1974,1975?', 'Answer': 1975.0} ,
{'Question': 'Amerykańskie Towarzystwo Zapobiegania Okrucieństwu wobec Zwierząt (aspca) powstało w którym roku?', 'Answer': 1866.0} ,
{'Question': 'Deklaracja Balfoura przez Wielką Brytanię była w którym roku?', 'Answer': 1917.0} ,
{'Question': 'Brodwayowska wersja disneyowskiego "Króla Lwa" używa więcej niż ___________ kukiełek?', 'Answer': 232.0} ,
{'Question': 'Charleston został wprowadzony na rynek w którym roku?', 'Answer': 1925.0} ,
{'Question': 'Chińczycy używali aluminium do produkcji rzeczy już w ___ ad?', 'Answer': 300.0} ,
{'Question': 'Film "Kolor pieniędzy" z Paulem Newmanem w roli głównej został wydany w tym roku?', 'Answer': 1986.0} ,
{'Question': 'Piosenka The Cranberries "Zombie" została wydana w którym roku?', 'Answer': 1994.0} ,
{'Question': 'W którym roku odkryto Zwoje znad Morza Martwego?', 'Answer': 1947.0} ,
{'Question': 'System dźwięku Dolby został wprowadzony w którym roku?', 'Answer': 1967.0} ,
{'Question': 'Reprezentacja Anglii na mistrzostwach świata w piłce nożnej wydała piosenkę Back Home w którym roku?', 'Answer': 1970.0} ,
{'Question': 'Pierwszy finał Pucharu Fa na Wembley, który wymagał powtórki, odbył się w którym roku?', 'Answer': 1970.0} ,
{'Question': 'W którym roku Floryda Martins wygrali World Series baseballu?', 'Answer': 1997.0} ,
{'Question': 'W którym roku Graf Zeppelin zakończył podróż na dystansie 19 500 mil?', 'Answer': 1929.0} ,
{'Question': 'Wielka Rafa Koralowa ma ile mil długości.?', 'Answer': 1250.0} ,
{'Question': 'Ile liter składa się na hawajski alfabet?', 'Answer': 12.0} ,
{'Question': 'W którym roku został opublikowany "Ogar Baskerville\'ów"?', 'Answer': 1903.0} ,
{'Question': 'W którym roku otwarto Astrodomę w Houston?', 'Answer': 1965.0} ,
{'Question': 'W którym roku został wydany film "Człowiek, który został królem?', 'Answer': 1975.0} ,
{'Question': 'Rów Mariański jest najgłębszym miejscem Oceanu Spokojnego, do jakiej głębokości sięga. Podaj odpowiedź w stopach.?', 'Answer': 36160.0} ,
{'Question': 'Mola Mola, lub Ocean Sunfish, składa do __________ jaj za jednym razem.?', 'Answer': 5000000.0} ,
{'Question': 'W którym roku hitem był utwór Monkees "I\'m A Believer"?', 'Answer': 1967.0} ,
{'Question': 'Czerwony Krzyż został zainicjowany w którym roku?', 'Answer': 1862.0} ,
{'Question': 'Armia Zbawienia została założona w którym roku?', 'Answer': 1865.0} ,
{'Question': 'Łuk bramny w St. Louis miał przewidywaną liczbę ofiar śmiertelnych podczas jego budowy. Ile osób zginęło?', 'Answer': 0.0} ,
{'Question': 'W którym roku Kanał Sueski został znacjonalizowany?', 'Answer': 1950.0} ,
{'Question': 'Stany Zjednoczone składają się z __ stanów.?', 'Answer': 50.0} ,
{'Question': 'Kąty w kwadracie mają w sumie _______ stopni?', 'Answer': 360.0} ,
{'Question': 'Kąty w kwadracie mają w sumie _______ stopni.?', 'Answer': 360.0} ,
{'Question': 'Przeciętny Amerykanin wypija około ilu napojów gazowanych rocznie.?', 'Answer': 600.0} ,
{'Question': 'Ile litrów wody zużywa przeciętna zmywarka automatyczna na jeden cykl zmywania?', 'Answer': 68.0} ,
{'Question': 'Ile dolarów rocznie traci przeciętny kasjer bankowy.?', 'Answer': 250.0} ,
{'Question': 'Przeciętna krowa produkuje __________ szklanek mleka każdego dnia.?', 'Answer': 40.0} ,
{'Question': 'Przeciętne ludzkie ciało zawiera wystarczającą ilość tłuszczu, aby wyprodukować ile kostek mydła?', 'Answer': 7.0} ,
{'Question': 'Przeciętne ludzkie ciało zawiera wystarczająco dużo żelaza, aby wyprodukować ile 3" gwoździ?', 'Answer': 1.0} ,
{'Question': 'Przeciętne ludzkie ciało zawiera wystarczająco dużo fosforu, aby wyprodukować ile główek zapałek?', 'Answer': 2000.0} ,
{'Question': 'Przeciętny człowiek produkuje ile kwart plwociny w ciągu życia?', 'Answer': 25000.0} ,
{'Question': 'Średnia minimalna prędkość ptaków, aby utrzymać się w locie, wynosi około 161/2 stopy na sekundę lub około __________ mil na godzinę.?', 'Answer': 11.0} ,
{'Question': 'Podstawa wielkiej piramidy w Egipcie jest wystarczająco duża, aby pokryć ile boisk piłkarskich?', 'Answer': 10.0} ,
{'Question': 'W którym roku książka "Sto lat samotności" otrzymała literacką Nagrodę Nobla?', 'Answer': 1982.0} ,
{'Question': 'Kompozytor Berlioz poślubił Harriet Smithson w którym roku?', 'Answer': 1833.0} ,
{'Question': 'W którym roku dolar został ustanowiony oficjalną walutą Stanów Zjednoczonych?', 'Answer': 1785.0} ,
{'Question': 'Ile mil wynosi obwód Ziemi w przybliżeniu?', 'Answer': 24870.0} ,
{'Question': 'W którym roku odbył się słynny festiwal muzyczny Woodstock?', 'Answer': 1969.0} ,
{'Question': 'Najszybszym ptakiem jest jerzyk o grzbietowym ogonie. Jak szybko może latać (mph)?', 'Answer': 106.0} ,
{'Question': 'W którym roku odbyła się premiera filmu "Żona biskupa"?', 'Answer': 1947.0} ,
{'Question': 'Film "Czarnoksiężnik z Oz" został wydany w którym roku?', 'Answer': 1939.0} ,
{'Question': 'Film "Chinatown" został wydany w którym roku?', 'Answer': 1974.0} ,
{'Question': 'Pierwszy "mówiący" film ukazał się w którym roku?', 'Answer': 1927.0} ,
{'Question': 'W którym roku ukazała się pierwsza amerykańska reklama tytoniu?', 'Answer': 1789.0} ,
{'Question': 'W którym roku wystrzelono pierwszego amerykańskiego satelitę?', 'Answer': 1958.0} ,
{'Question': 'W którym roku z taśmy montażowej Chevroleta we Flint, MI. zjechała pierwsza Corvette?', 'Answer': 1953.0} ,
{'Question': 'W którym roku odbył się pierwszy międzynarodowy mecz piłki nożnej z użyciem reflektorów?', 'Answer': 1955.0} ,
{'Question': 'W którym roku wystrzelono pierwszego rosyjskiego satelitę?', 'Answer': 1957.0} ,
{'Question': 'W którym roku odbył się pierwszy załogowy lot balonem?', 'Answer': 1783.0} ,
{'Question': 'Pierwszym przedmiotem handlowym, na którym pojawiła się Myszka Miki, był dziecięcy tablet szkolny w _________.?', 'Answer': 1929.0} ,
{'Question': 'W którym roku jako pierwsza osoba przepłynęła kanał La Manche?', 'Answer': 1875.0} ,
{'Question': 'W którym roku nakręcono pierwszy spaghetti western z Clintem Eastwoodem w roli głównej?', 'Answer': 1964.0} ,
{'Question': 'W tym roku w Ameryce pojawił się pierwszy silnik parowy?', 'Answer': 1753.0} ,
{'Question': 'W którym roku wykonano pierwszą rozmowę telefoniczną?', 'Answer': 1876.0} ,
{'Question': 'W którym roku otwarto pierwszą centralę telefoniczną w USA?', 'Answer': 1878.0} ,
{'Question': 'Budowę wielkiej gotyckiej katedry w Mediolanie rozpoczęto w 1386 r., a ukończono dopiero w którym roku?', 'Answer': 1805.0} ,
{'Question': 'Budowa wielkiej gotyckiej katedry w Mediolanie rozpoczęła się w 1386 roku i zakończyła się dopiero w którym roku?', 'Answer': 1805.0} ,
{'Question': 'Największy opad śniegu podczas jednej burzy wyniósł ___ cali w Mount Shasta Ski bowl w lutym 1959 roku.?', 'Answer': 189.0} ,
{'Question': 'W którym roku wynaleziono hamburgera?', 'Answer': 1900.0} ,
{'Question': 'Najwyższa temperatura stworzona przez człowieka wynosiła ___. milionów stopni Celsjusza?', 'Answer': 70.0} ,
{'Question': 'Najwyższa temperatura, jaką kiedykolwiek zanotowano, wystąpiła w Libii w 1922 roku. Jaka to była temperatura (fahrenehit)?', 'Answer': 136.0} ,
{'Question': 'Najwyższy wodospad na świecie, Angel Falls w Wenezueli, ma łączny spadek ilu stóp.?', 'Answer': 3121.0} ,
{'Question': 'Lody sodowe zostały wynalezione w którym roku?', 'Answer': 1874.0} ,
{'Question': 'W którym roku odbył się inauguracyjny maraton londyński?', 'Answer': 1981.0} ,
{'Question': 'Pojedyncze włosy szynszyli są tak cienkie, że __________ z nich równa się grubości pojedynczego ludzkiego włosa.?', 'Answer': 500.0} ,
{'Question': 'Wyspa Krakatoa została prawie całkowicie zniszczona przez wybuch wulkanu w którym roku?', 'Answer': 1883.0} ,
{'Question': 'Ile razy duża maszyna do obracania diamentów w optyce przecięła pojedynczy ludzki włos wzdłuż, ile razy?', 'Answer': 3000.0} ,
{'Question': 'W którym roku zbudowano największy zegar słoneczny?', 'Answer': 1724.0} ,
{'Question': 'Ostatnim dniem publicznej eksploatacji Liverpool Overhead Railway był 30 grudnia którego roku?', 'Answer': 1956.0} ,
{'Question': 'W którym roku powstało czasopismo medyczne The Lancet?', 'Answer': 1823.0} ,
{'Question': 'Ile centów za godzinę wynosiła płaca minimalna w 1938 roku?', 'Answer': 25.0} ,
{'Question': 'W którym roku wynaleziono rower z pedałami?', 'Answer': 1839.0} ,
{'Question': 'W którym roku odkryto planetę Pluton?', 'Answer': 1930.0} ,
{'Question': 'Rośliny żyjące w oceanach stanowią około jakiego procenta całej zieleni na Ziemi?', 'Answer': 85.0} ,
{'Question': 'W którym roku ziemniak dotarł do Hiszpanii?', 'Answer': 1565.0} ,
{'Question': 'Od którego roku prowincja Alberta w Kanadzie jest całkowicie wolna od szczurów?', 'Answer': 1905.0} ,
{'Question': 'Prędkość względna TRS-80 w stosunku do ENIACa wynosi __:1.?', 'Answer': 20.0} ,
{'Question': 'W którym roku opatentowano maszynę do szycia?', 'Answer': 1846.0} ,
{'Question': 'W którym roku miała miejsce najkrótsza wojna pomiędzy Wielką Brytanią a Zanzibarem?', 'Answer': 1896.0} ,
{'Question': 'Piosenka "Why Do Fools Fall in Love" była hitem w którym roku?', 'Answer': 1956.0} ,
{'Question': 'Pierwiastek kwadratowy z 1 to?', 'Answer': 1.0} ,
{'Question': 'Pierwiastek kwadratowy z 1 to?', 'Answer': 1.0} ,
{'Question': 'W którym roku wynaleziono telefon?', 'Answer': 1876.0} ,
{'Question': 'Ile lat liczy sobie dwusetna rocznica ?', 'Answer': 200.0} ,
{'Question': 'Ile lat liczy sobie stulecie?', 'Answer': 100.0} ,
{'Question': 'Ile lat liczy sobie termin Quadricentennial?', 'Answer': 400.0} ,
{'Question': 'Ile lat liczy sobie termin Kwartocentrum?', 'Answer': 25.0} ,
{'Question': 'Ile lat reprezentuje termin Quincentennial?', 'Answer': 500.0} ,
{'Question': 'Ile lat liczy sobie termin Półwiecze?', 'Answer': 50.0} ,
{'Question': 'Ile lat reprezentuje termin Septiquinquennial?', 'Answer': 75.0} ,
{'Question': 'Ile lat reprezentuje termin Sesquibicentennial?', 'Answer': 250.0} ,
{'Question': 'Ile lat reprezentuje termin Sesquincentennial?', 'Answer': 150.0} ,
{'Question': 'Ile lat reprezentuje termin Sesquiquadricentennial?', 'Answer': 450.0} ,
{'Question': 'Ile lat reprezentuje termin Sesquitercentennial?', 'Answer': 350.0} ,
{'Question': 'Ile lat reprezentuje termin Tercentennial?', 'Answer': 300.0} ,
{'Question': 'W którym roku po raz pierwszy wykonano utwór Rhapsody in Blue?', 'Answer': 1924.0} ,
{'Question': 'W którym roku wojna w Wietnamie zakończyła się upadkiem Sajgonu?', 'Answer': 1975.0} ,
{'Question': 'Koło zostało wynalezione mniej więcej w którym roku p.n.e.?', 'Answer': 3500.0} ,
{'Question': 'Jaki jest najlepszy wynik w blackjacku?', 'Answer': 21.0} ,
{'Question': 'Największy ssak na świecie, wieloryb błękitny, waży 50 ton po urodzeniu. W pełni rozwinięty waży aż __________ ton.?', 'Answer': 150.0} ,
{'Question': 'Największym gryzoniem na świecie jest kapibara. Amazońska świnia wodna, która wygląda jak świnka morska, może ważyć więcej niż __________ funtów.?', 'Answer': 100.0} ,
{'Question': 'W którym roku wyprodukowano pierwszy na świecie cukierek czekoladowy?', 'Answer': 1828.0} ,
{'Question': 'Najgorszy pożar cyrku miał miejsce w USA w którym roku?', 'Answer': 1944.0} ,
{'Question': 'Najgorsza katastrofa sportowa miała miejsce w Hongkongu, kiedy to w którym roku zawaliły się trybuny na torze wyścigowym zabijając 604 osoby.?', 'Answer': 1918.0} ,
{'Question': 'Na Antarktydzie znajdują się 42 inne całoroczne stacje badawcze. W sumie, około __________ osób mieszka na Antarktydzie latem, 1000 zimą.?', 'Answer': 4000.0} ,
{'Question': 'W tym układzie słonecznym jest _planet.?', 'Answer': 9.0} ,
{'Question': 'Ile kilometrów nerwów znajduje się w skórze człowieka?', 'Answer': 45.0} ,
{'Question': 'W Perquackey jest tyle czerwonych_literowych kostek.?', 'Answer': 3.0} ,
{'Question': 'Do którego roku na wyspie Nantucket w stanie Massachusetts nie było wiewiórek.?', 'Answer': 1989.0} ,
{'Question': 'Film "Coś jest w Mary" z Cameron Diaz w roli głównej został wydany w którym roku?', 'Answer': 1998.0} ,
{'Question': 'To jest długość, w stopach, regulaminowego stołu do snookera.?', 'Answer': 12.0} ,
{'Question': 'W którym roku urodził się Thomas Cook, agent biura podróży?', 'Answer': 1808.0} ,
{'Question': 'W którym roku Thomas Edison po raz pierwszy zademonstrował światło elektryczne?', 'Answer': 1879.0} ,
{'Question': 'Thomas Young, fizyk i egiptolog, w wieku 14 lat mówił w ilu językach?', 'Answer': 12.0} ,
{'Question': 'Do 10 lat w obie strony W którym roku Sir Francis Drake rozpoczął swoją podróż dookoła świata?', 'Answer': 1577.0} ,
{'Question': 'Do 25 lat w obie strony W którym roku urodził się "Robert The Bruce"?', 'Answer': 1274.0} ,
{'Question': 'W którym roku, aby przesyłać transatlantyckie wiadomości telegraficzne, położono pod Atlantykiem 3000 mil kabla?', 'Answer': 1886.0} ,
{'Question': 'Z dokładnością do 0,1 km, ile kilometrów mieści się w mili?', 'Answer': 1.6} ,
{'Question': 'Jak daleko od Ziemi znajduje się Słońce z dokładnością do miliona mil?', 'Answer': 93.0} ,
{'Question': 'Z dokładnością do 3 mph, przy jakiej prędkości w m.p.h. wiatr staje się huraganem?', 'Answer': 73.0} ,
{'Question': 'Z dokładnością do 30 stóp, jak wysoka jest wieża Eiffla?', 'Answer': 984.0} ,
{'Question': 'Najstarszą współczesną formą konia jest Przewalski, czyli dziki koń mongolski. Ocalałe osobniki tej rasy zostały odkryte na pustyni Gobi w __________.?', 'Answer': 1881.0} ,
{'Question': 'W którym roku w Londynie po raz pierwszy użyto sygnalizacji świetlnej?', 'Answer': 1869.0} ,
{'Question': 'Dwie baterie o napięciu 1,5 V połączone szeregowo dają napięcie _ V.?', 'Answer': 3.0} ,
{'Question': 'Do kiedy Kalifornia była częścią Meksyku?', 'Answer': 1846.0} ,
{'Question': 'Walencja kiedy pierwszy człowiek chodził po księżycu?', 'Answer': 1968.0} ,
{'Question': 'Van Gogh zaczął rysować w wieku?', 'Answer': 27.0} ,
{'Question': 'Wyspa Vancover i Kolumbia Brytyjska stały się jedną kolonią w?', 'Answer': 1866.0} ,
{'Question': 'W którym roku Vasco da Gama opłynął Przylądek Dobrej Nadziei?', 'Answer': 1498.0} ,
{'Question': 'Ile księżyców ma Wenus?', 'Answer': 0.0} ,
{'Question': 'Vince Lombardi i Brian Picollo zmarli na stronie _____?', 'Answer': 1970.0} ,
{'Question': 'Wadsworth W którym roku wprowadzono Diet Pepsi?', 'Answer': 1965.0} ,
{'Question': 'Czy utwór Phila Collinsa "Another Day In Paradise" został wydany w 1983 czy 1989 roku?', 'Answer': 1989.0} ,
{'Question': 'Czy Shirley Temple miała 21, 25 czy 29 lat, kiedy nakręciła swój ostatni film?', 'Answer': 21.0} ,
{'Question': 'Woda zamarza w temperaturze _ stopni Celcjusza.?', 'Answer': 0.0} ,
{'Question': 'Woda zamarza w temperaturze __ stopni Fahrenheita.?', 'Answer': 32.0} ,
{'Question': 'Jaka książka z 1949 roku stała się bestsellerem 35 lat później?', 'Answer': 1984.0} ,
{'Question': 'Jaką podstawą są liczby szesnastkowe?', 'Answer': 16.0} ,
{'Question': 'Do czego sprowadzają się słowa w pierwszej linijce piosenki Elvisa Presleya "Blue Suede Shoes"?', 'Answer': 6.0} ,
{'Question': 'Jaką sumę mają zawsze przeciwległe strony standardowej kostki do gry?', 'Answer': 7.0} ,
{'Question': 'Co to jest grzech? A+ Cos? Równa się?', 'Answer': 1.0} ,
{'Question': 'Co to jest dziesięć w notacji binarnej?', 'Answer': 1010.0} ,
{'Question': 'Jaka jest maksymalna liczba kijów w torbie golfowej?', 'Answer': 14.0} ,
{'Question': 'Jaka jest maksymalna liczba koni, które mogą wystartować w Grand National?', 'Answer': 40.0} ,
{'Question': 'Co to jest liczba dziesięć w notacji binarnej?', 'Answer': 1010.0} ,
{'Question': 'Jaka jest jedyna parzysta liczba pierwsza?', 'Answer': 2.0} ,
{'Question': 'Co to jest pierwiastek kwadratowy z 144?', 'Answer': 12.0} ,
{'Question': 'Co to jest wartość sinusa 30 stopni?', 'Answer': 0.5} ,
{'Question': 'Jaka liczba jest często nazywana (Clickety Click) w Bingo?', 'Answer': 66.0} ,
{'Question': 'Jaka liczba jest napisana na odwrocie koszulki Davida Beckhama, kiedy grał dla Realu Madryt?', 'Answer': 23.0} ,
{'Question': 'Jaka liczba znajduje się pomiędzy 15 a 6 na tarczy do gry w rzutki?', 'Answer': 10.0} ,
{'Question': 'Jaką pozycję na brytyjskiej liście przebojów osiągnął utwór ACDC Hightway To Hell w 1979 roku 1, 4 lub 56?', 'Answer': 56.0} ,
{'Question': 'Jaką wartość ma PI do 6 cyfr znaczących?', 'Answer': 3.141592} ,
{'Question': 'Jaki był rok koronacji królowej Elżbiety 2.?', 'Answer': 1952.0} ,
{'Question': 'Jaka była najwyższa pozycja na brytyjskiej liście przebojów osiągnięta przez U2 w 1981 roku z singlem "Gloria"?', 'Answer': 55.0} ,
{'Question': 'W którym roku wprowadzono w Polsce stan wojenny?', 'Answer': 1918.0} ,
{'Question': 'W którym roku wydano utwór "Like A Virgin" Madonny?', 'Answer': 1984.0} ,
{'Question': 'W którym roku ukazał się utwór Prince\'a "When Doves Cry"?', 'Answer': 1984.0} ,
{'Question': 'Do jakiej sumy sumują się kropki na parze kostek do gry?', 'Answer': 42.0} ,
{'Question': 'Jaka gra zazwyczaj zaczyna się od słów "czy to zwierzę, warzywo czy minerał"?', 'Answer': 20.0} ,
{'Question': 'Ile to jest 1 dzień i 2 godziny w godzinach?', 'Answer': 26.0} ,
{'Question': 'Ile to jest 3 dni i 6 godzin w minutach?', 'Answer': 4680.0} ,
{'Question': 'Ile to jest 32 dziesiętnie wyrażone w systemie szesnastkowym?', 'Answer': 20.0} ,
{'Question': 'Ile to jest 65% z 60?', 'Answer': 39.0} ,
{'Question': 'Co to jest 65% z sześćdziesięciu?', 'Answer': 39.0} ,
{'Question': 'Ile to jest 7 dni i 10 godzin w minutach?', 'Answer': 10680.0} ,
{'Question': 'Jaki jest najlepszy czas Linforda Christiesa w biegu na 100 metrów?', 'Answer': 9.87} ,
{'Question': 'Jaka jest inna nazwa gry karcianej "Blackjack"?', 'Answer': 21.0} ,
{'Question': "Jaka jest inna nazwa gry karcianej 'blackjack'?", 'Answer': 21.0} ,
{'Question': 'Co to jest ix?', 'Answer': 9.0} ,
{'Question': 'Co jest następne w serii 1 8 27 ??? 125 216?', 'Answer': 64.0} ,
{'Question': 'Jaki jest "doskonały wynik" w grze w kręgle na dziesięciu kołkach?', 'Answer': 300.0} ,
{'Question': 'Co to jest cyfra rzymska mcdxlii w systemie dziesiętnym?', 'Answer': 1442.0} ,
{'Question': "Jaka jest odpowiedź na pytanie o sens życia według Douglasa Adamsa w 'Autostopem przez galaktykę'?", 'Answer': 42.0} ,
{'Question': 'Jaki jest kod obszaru dla statków wycieczkowych na Oceanie Atlantyckim?', 'Answer': 871.0} ,
{'Question': 'Jaka jest masa atomowa bromu?', 'Answer': 79.9} ,
{'Question': 'Jaka jest masa atomowa molibdenu?', 'Answer': 95.94} ,
{'Question': 'Jaka jest masa atomowa platyny?', 'Answer': 195.09} ,
{'Question': 'Jaka jest masa atomowa siarki?', 'Answer': 32.06} ,
{'Question': 'Jaka jest liczba atomowa wodoru (h)?', 'Answer': 1.0} ,
{'Question': 'Jaka jest liczba atomowa talu?', 'Answer': 81.0} ,
{'Question': 'Jaka jest liczba atomowa talu?', 'Answer': 81.0} ,
{'Question': 'Jaka jest liczba atomowa cezu?', 'Answer': 55.0} ,
{'Question': 'Jaka jest liczba atomowa siarki?', 'Answer': 16.0} ,
{'Question': 'Jaka jest liczba atomowa wolframu?', 'Answer': 74.0} ,
{'Question': 'Jaka jest liczba atomowa uranu?', 'Answer': 92.0} ,
{'Question': 'Jaka jest masa atomowa arsenu?', 'Answer': 75.0} ,
{'Question': 'Jaka jest masa atomowa uranu?', 'Answer': 92.0} ,
{'Question': 'Jaki jest najlepszy możliwy wynik w blackjacku?', 'Answer': 21.0} ,
{'Question': 'Jaki jest najlepszy wynik w blackjacku?', 'Answer': 21.0} ,
{'Question': 'Jaki jest binarny odpowiednik dziesiętnej liczby 10?', 'Answer': 1010.0} ,
{'Question': 'Jaka jest temperatura wrzenia wody w skali Fahrenheita?', 'Answer': 212.0} ,
{'Question': 'Jaki jest wzór chemiczny ozonu?', 'Answer': 3.0} ,
{'Question': 'Jaki jest numer karny jeana valjeana w "les miserables"?', 'Answer': 24601.0} ,
{'Question': 'Jaki jest numer karny boba w "The Simpsons"?', 'Answer': 24601.0} ,
{'Question': 'Jaka jest data na butelkach wódki Smirnoff?', 'Answer': 1818.0} ,
{'Question': 'Jaki jest dziesiętny odpowiednik liczby binarnej 11011?', 'Answer': 27.0} ,
{'Question': 'Jaka jest pierwsza liczba pierwsza po 1,000,000?', 'Answer': 1000003.0} ,
{'Question': 'Jaki jest międzynarodowy kod telefoniczny dla Wielkiej Brytanii?', 'Answer': 44.0} ,
{'Question': 'Jaki jest międzynarodowy kod telefoniczny dla Antarktydy?', 'Answer': 672.0} ,
{'Question': 'Jaka jest maksymalna liczba stopni w kącie rozwartym?', 'Answer': 179.9} ,
{'Question': 'Jaka jest maksymalna liczba stopni całkowitych w kącie rozwartym?', 'Answer': 359.0} ,
{'Question': 'Jaka jest maksymalna liczba stopni całkowitych w kącie ostrym?', 'Answer': 89.0} ,
{'Question': 'Jaka jest maksymalna liczba stopni całkowitych w kącie rozwartym?', 'Answer': 179.0} ,
{'Question': 'Jaki jest minimalny wynik IQ dla kategorii geniusza?', 'Answer': 140.0} ,
{'Question': 'Jaki jest minimalny wynik IQ dla kategorii geniusza?', 'Answer': 140.0} ,
{'Question': 'Jaka jest minimalna liczba stopni w kącie rozwartym?', 'Answer': 180.0} ,
{'Question': 'Jaka jest minimalna liczba stopni całkowitych w kącie rozwartym?', 'Answer': 181.0} ,
{'Question': 'Jaka jest minimalna liczba stopni całkowitych w kącie rozwartym?', 'Answer': 91.0} ,
{'Question': 'Jaki jest ostatni rok, który może być napisany do góry nogami i do prawej strony i nadal wygląda tak samo?', 'Answer': 1961.0} ,
{'Question': 'Jaka jest liczba bestii?', 'Answer': 666.0} ,
{'Question': 'Jaki jest zasięg, w milach, wróbla Aim-7?', 'Answer': 28.0} ,
{'Question': 'Ile wynosi pierwiastek kwadratowy z 144?', 'Answer': 12.0} ,
{'Question': 'Ile wynosi pierwiastek kwadratowy z 4096?', 'Answer': 64.0} ,
{'Question': 'Ile wynosi pierwiastek kwadratowy z 65536?', 'Answer': 256.0} ,
{'Question': 'Ile wynosi pierwiastek kwadratowy z sumy 55+65+24?', 'Answer': 12.0} ,
{'Question': 'Ile wynosi suma 236 - 145?', 'Answer': 91.0} ,
{'Question': 'Ile wynosi suma 27 + 52?', 'Answer': 79.0} ,
{'Question': 'Ile wynosi suma 2741 + 3562?', 'Answer': 6303.0} ,
{'Question': 'Ile wynosi suma 32 + 49 + 765?', 'Answer': 846.0} ,
{'Question': 'Jaka jest suma 4 x 4 x 24 x 44?', 'Answer': 16896.0} ,
{'Question': 'Ile wynosi suma 444 x 2 x 2 - 1700?', 'Answer': 76.0} ,
{'Question': 'Ile wynosi suma 67 + 67 + 67 + 67 + 67?', 'Answer': 365.0} ,
{'Question': 'Jaka jest suma 91 x 452?', 'Answer': 41132.0} ,
{'Question': 'Jaka jest suma 95 x 1?', 'Answer': 95.0} ,
{'Question': 'Ile wynosi suma wszystkich kątów w kwadracie? (w stopniach)?', 'Answer': 360.0} ,
{'Question': 'Jaki jest numer patentowy telefonu w USA?', 'Answer': 174465.0} ,
{'Question': 'Jaką maksymalną prędkość w milach na godzinę osiągają gepardy?', 'Answer': 71.0} ,
{'Question': 'Jaka jest wartość liczby pi z dokładnością do trzech miejsc po przecinku?', 'Answer': 3.142} ,
{'Question': 'Jaki numer widniał na boku samochodu "Herbie" w serii filmów?', 'Answer': 53.0} ,
{'Question': 'Jaką liczbę umieścił Levi Strauss na pierwszej sprzedanej parze dżinsów?', 'Answer': 501.0} ,
{'Question': 'Jaka liczba znajduje się na godzinie 12 na tarczy do gry w rzutki?', 'Answer': 20.0} ,
{'Question': 'Jaka liczba znajduje się na godzinie 12 na tarczy do rzutek?', 'Answer': 20.0} ,
{'Question': 'Jaką liczbę ma Pokémon "Scyther" w grach Pokémon GameBoy?', 'Answer': 123.0} ,
{'Question': 'Jaka liczba jest używana do reprezentowania szatana?', 'Answer': 666.0} ,
{'Question': "Jaki numer koszulki był synonimem legendy hokeja na lodzie Wayne'a Gtrezky'ego?", 'Answer': 99.0} ,
{'Question': 'Jaka liczba leży pomiędzy 1 i 5 na tarczy do rzutek?', 'Answer': 20.0} ,
{'Question': 'Jakie liczby można znaleźć na odwrocie amerykańskiego banknotu 5-dolarowego w krzakach u podnóża pomnika Lincolna?', 'Answer': 172.0} ,
{'Question': 'Jakiego procentu od sprzedaży biletów żądał artur rubenstein od koncertów?', 'Answer': 70.0} ,
{'Question': 'Jaki procent orzeszka ziemnego stanowi tłuszcz?', 'Answer': 47.0} ,
{'Question': 'Jaki procent skorupy ziemskiej jest słony?', 'Answer': 92.0} ,
{'Question': 'Jaki procent masy ciała stanowi woda 30, 50 lub 70 procent?', 'Answer': 70.0} ,
{'Question': 'Jaki wynik nie jest możliwy do uzyskania przez rękę grającą w cribbage?', 'Answer': 19.0} ,
{'Question': 'Jaki numer munduru nosili Larry Bird i Kareem Abdul Jabbar?', 'Answer': 33.0} ,
{'Question': 'Jakie napięcie ma większość akumulatorów samochodowych?', 'Answer': 12.0} ,
{'Question': 'Jaki był numer sieci Maxa Headrooma?', 'Answer': 23.0} ,
{'Question': 'W którym roku po raz pierwszy kobiety mogły głosować w Norwegii?', 'Answer': 1913.0} ,
{'Question': 'Jaki był numer jednostki M.A.S.H. w filmie i serialu telewizyjnym o tej samej nazwie?', 'Answer': 4077.0} ,
{'Question': 'Jaki był numer dywizjonu, który w 1943 roku wykonał misję Dambusters?', 'Answer': 617.0} ,
{'Question': 'W którym roku zmarł "Papa Doc", prezydent Haiti?', 'Answer': 1967.0} ,
{'Question': 'W którym roku Brasilia została stolicą Brazylii?', 'Answer': 1960.0} ,
{'Question': 'W którym roku Honduras Brytyjski stał się Belize?', 'Answer': 1973.0} ,
{'Question': 'W którym roku wybuchł Czarnobyl?', 'Answer': 1986.0} ,
{'Question': 'W którym roku Chet Atkins wydał swój pierwszy solowy album?', 'Answer': 1953.0} ,
{'Question': 'W którym roku Emily Pankhurst przykuła się do Downing Street 10?', 'Answer': 1907.0} ,
{'Question': 'W którym roku George Washington został prezydentem Stanów Zjednoczonych?', 'Answer': 1789.0} ,
{'Question': 'W którym roku Laurel i Hardy po raz pierwszy wystąpili razem?', 'Answer': 1926.0} ,
{'Question': 'W którym roku Neil Armstrong wylądował na Księżycu?', 'Answer': 1969.0} ,
{'Question': 'W którym roku Red Rum po raz pierwszy wygrał Grand National?', 'Answer': 1973.0} ,
{'Question': 'W którym roku Roger Maris zdobył 61 homerunów?', 'Answer': 1961.0} ,
{'Question': 'W którym roku zmarł Theodore Roosevelt?', 'Answer': 1919.0} ,
{'Question': 'W którym roku Jurij Gagarin został pierwszym człowiekiem w kosmosie?', 'Answer': 1961.0} ,
{'Question': 'W którym roku coca-cola po raz pierwszy trafiła do sprzedaży?', 'Answer': 1886.0} ,
{'Question': 'W którym roku zmarł sir Richard Whittington?', 'Answer': 1423.0} ,
{'Question': 'W którym roku miała miejsce "Zatoka Świń"?', 'Answer': 1961.0} ,
{'Question': 'W którym roku bolszewicy obalili rząd rosyjski?', 'Answer': 1917.0} ,
{'Question': 'W którym roku pierwszy rocznik wyżu demograficznego skończył 50 lat?', 'Answer': 1996.0} ,
{'Question': 'W którym roku otwarto pierwszy motel?', 'Answer': 1925.0} ,
{'Question': 'W którym roku otwarto pierwszą kolonię nudystów?', 'Answer': 1903.0} ,
{'Question': 'W którym roku zgasły światła?', 'Answer': 1965.0} ,
{'Question': 'W którym roku nastąpił wielki krach giełdowy, który doprowadził do wielkiej depresji?', 'Answer': 1929.0} ,
{'Question': 'W którym roku cukier podrożał z dziewięciu centów do pięćdziesięciu ośmiu centów za funt?', 'Answer': 1973.0} ,
{'Question': 'W którym roku wystrzelono Sputnika I?', 'Answer': 1957.0} ,
{'Question': 'W którym roku urodził się Aaron Copeland?', 'Answer': 1900.0} ,
{'Question': 'W którym roku został zamordowany arcyksiążę Ferdynand?', 'Answer': 1914.0} ,
{'Question': 'W którym roku wynaleziono mąkę naleśnikową Aunt Jemima?', 'Answer': 1889.0} ,
{'Question': 'W którym roku po raz pierwszy określono DNA?', 'Answer': 1953.0} ,
{'Question': 'W którym roku schwytano Geronimo?', 'Answer': 1886.0} ,
{'Question': 'W którym roku Margaret Thatcher została wybrana na premiera Wielkiej Brytanii?', 'Answer': 1979.0} ,
{'Question': 'W którym roku powstała NASA?', 'Answer': 1958.0} ,
{'Question': 'W którym roku odkryto Neptuna?', 'Answer': 1846.0} ,
{'Question': 'W którym roku urodził się Picasso?', 'Answer': 1881.0} ,
{'Question': 'W którym roku Robert the Bruce został koronowany na króla Szkocji?', 'Answer': 1306.0} ,
{'Question': 'W którym roku wydrukowano Biblię przy użyciu ruchomej czcionki?', 'Answer': 1455.0} ,
{'Question': 'W którym roku urodził się Theodore Roosevelt?', 'Answer': 1858.0} ,
{'Question': 'W którym roku urodził się Walt Disney?', 'Answer': 1901.0} ,
{'Question': 'W którym roku pilot U2 został zestrzelony za szpiegostwo?', 'Answer': 1960.0} ,
{'Question': 'W którym roku wprowadzono film, który zastąpił szkło w produkcji negatywów fotograficznych?', 'Answer': 1891.0} ,
{'Question': 'W którym roku zwodowano pierwszą amerykańską atomową łódź podwodną?', 'Answer': 1954.0} ,
{'Question': 'W którym roku odbyła się bitwa pod Bannockburn?', 'Answer': 1314.0} ,
{'Question': 'W którym roku założono firmę Habitat?', 'Answer': 1971.0} ,
{'Question': 'W którym roku odbył się koncert Live Aid?', 'Answer': 1985.0} ,
{'Question': 'W którym roku odbyła się premiera filmu Bacall-Bogart "Chłopaki z Milwaukee"?', 'Answer': 1946.0} ,
{'Question': 'W którym roku wynaleziono wiertło dentystyczne?', 'Answer': 1790.0} ,
{'Question': 'W którym roku odbyła się premiera filmu "Otchłań"?', 'Answer': 1989.0} ,
{'Question': 'W którym roku otwarto pierwszą komercyjną operę?', 'Answer': 1637.0} ,
{'Question': 'W którym roku odbył się pierwszy wyścig motocyklowy?', 'Answer': 1907.0} ,
{'Question': 'W którym roku sprzedano pierwsze oreo?', 'Answer': 1912.0} ,
{'Question': 'W którym roku przeprowadzono pierwszą ekstrakcję zęba pod narkozą?', 'Answer': 1846.0} ,
{'Question': 'W którym roku rozegrano pierwszy mecz World Series?', 'Answer': 1903.0} ,
{'Question': 'W którym roku w Wielkiej Brytanii panowała wielka susza?', 'Answer': 1976.0} ,
{'Question': 'W którym roku wprowadzono procesor intel pentium?', 'Answer': 1993.0} ,
{'Question': 'W którym roku powieszono ostatnią kobietę w Anglii?', 'Answer': 1955.0} ,
{'Question': 'W którym roku odbyła się premiera filmu "Pluskwa miłości"?', 'Answer': 1969.0} ,
{'Question': 'W którym roku na Japonię zostały zrzucone dwie bomby atomowe?', 'Answer': 1945.0} ,
{'Question': 'W którym roku na Zimowych Igrzyskach Olimpijskich wprowadzono slalom gigant?', 'Answer': 1988.0} ,
{'Question': 'Co jest następne w serii 2, 3, 4, 6, 8, 12, 14, 18, 20, ?', 'Answer': 24.0} ,
{'Question': 'Jaka jest średnia roczna temperatura na świecie (w stopniach Fahrenheita)?', 'Answer': 58.0} ,
{'Question': 'Jaka jest średnia liczba morderstw, które dziecko widziało w telewizji przed ukończeniem 16 roku życia?', 'Answer': 18000.0} ,
{'Question': 'Jaki jest najwyższy możliwy wynik końcowy w grze w rzutki?', 'Answer': 167.0} ,
{'Question': 'Jaki jest telefoniczny numer kierunkowy do Chicago?', 'Answer': 312.0} ,
{'Question': 'Jaka jest wartość punktowa zewnętrznej kuli na tarczy do rzutek?', 'Answer': 25.0} ,
{'Question': 'Jaki jest telefoniczny numer kierunkowy do Chicago?', 'Answer': 312.0} ,
{'Question': 'Kiedy Ike & Tina Turner się rozstali?', 'Answer': 1976.0} ,
{'Question': 'Kiedy Napoleon Bonaparte rozpoczął swoje panowanie jako cesarz Francji?', 'Answer': 1804.0} ,
{'Question': 'Kiedy innowatorzy popu, Kraftwerk, zdobyli 11. miejsce na płycie Autobahn (1973, 1975, 1977, 1979)?', 'Answer': 1975.0} ,
{'Question': 'Kiedy Sid Vicious dołączył do Sex Pistols?', 'Answer': 1977.0} ,
{'Question': 'Kiedy The Beatles po raz pierwszy wydali Strawberry Fields?', 'Answer': 1967.0} ,
{'Question': 'Kiedy The Prodigy wydali "Fire"?', 'Answer': 1992.0} ,
{'Question': 'Kiedy zniesiono karę śmierci w Wielkiej Brytanii?', 'Answer': 1969.0} ,
{'Question': 'Kiedy zakończono budowę pierwszej kolei transkontynentalnej w Ameryce Północnej?', 'Answer': 1869.0} ,
{'Question': 'Kiedy Alaska stała się 49. stanem USA?', 'Answer': 1959.0} ,
{'Question': 'Kiedy zmarł Andy Warhol?', 'Answer': 1987.0} ,
{'Question': 'Kiedy Baden Powell założył ruch skautowski?', 'Answer': 1907.0} ,
{'Question': 'Kiedy Brazylia przeniosła swoją stolicę z Rio de Janeiro do Brasilii?', 'Answer': 1960.0} ,
{'Question': 'Kiedy Castro przejął władzę na Kubie?', 'Answer': 1959.0} ,
{'Question': 'Kiedy Boże Narodzenie stało się świętem federalnym w USA?', 'Answer': 1831.0} ,
{'Question': 'Kiedy wygasła dzierżawa Hongkongu przez Anglię?', 'Answer': 1997.0} ,
{'Question': 'Kiedy Henry Ford zbudował swój pierwszy samochód?', 'Answer': 1896.0} ,
{'Question': 'Kiedy Levi Strauss wyprodukował pierwsze dżinsy?', 'Answer': 1850.0} ,
{'Question': 'Kiedy Mark i Engels napisali Manifest Komunistyczny?', 'Answer': 1848.0} ,
{'Question': 'Kiedy papież Paweł Vl powiedział, że post jest nadal obowiązkowy w niektóre dni?', 'Answer': 1966.0} ,
{'Question': 'Kiedy Sir Walter Scott napisał "Ivanhoe"?', 'Answer': 1819.0} ,
{'Question': 'Kiedy William Lyon Mackenzie King przeszedł na emeryturę?', 'Answer': 1948.0} ,
{'Question': "Kiedy pierwszy rock and rollowy klasyk Chucka Berry'ego trafił na listy przebojów?", 'Answer': 1957.0} ,
{'Question': 'Kiedy otwarto Disneyland?', 'Answer': 1955.0} ,
{'Question': 'Kiedy człowiek po raz pierwszy postawił stopę na księżycu?', 'Answer': 1969.0} ,
{'Question': 'Kiedy skończyła się prohibicja w USA?', 'Answer': 1933.0} ,
{'Question': 'Kiedy skończyła się prohibicja w USA?', 'Answer': 1933.0} ,
{'Question': 'Kiedy zmarł richard burton?', 'Answer': 1984.0} ,
{'Question': 'Kiedy Richard Burton skończył swój ostatni film?', 'Answer': 1984.0} ,
{'Question': 'Kiedy odbyły się koncerty "live aid"?', 'Answer': 1985.0} ,
{'Question': 'Kiedy Imperium Brytyjskie przekształciło się w Wspólnotę Narodów?', 'Answer': 1931.0} ,
{'Question': 'Kiedy firma Fuller Brush Company zaczęła używać katalogów?', 'Answer': 1986.0} ,
{'Question': 'Kiedy odbył się pierwszy mecz World Series?', 'Answer': 1903.0} ,
{'Question': 'Kiedy New York Mets wygrali swoją pierwszą serię światową?', 'Answer': 1969.0} ,
{'Question': 'Kiedy serial "lost in space" miał premierę na cbs?', 'Answer': 1965.0} ,
{'Question': 'Kiedy makau powróciło do Chin?', 'Answer': 1999.0} ,
{'Question': 'Kiedy występuje południowa równonoc jesienna?', 'Answer': 42075.0} ,
{'Question': "Kiedy ma się pojawić kometa Halley'a?", 'Answer': 2062.0} ,
{'Question': 'Kiedy został wybrany Abraham Lincoln?', 'Answer': 1860.0} ,
{'Question': 'Kiedy ukończono budowę Big Bena?', 'Answer': 1858.0} ,
{'Question': "Kiedy wynaleziono druk Braille'a?", 'Answer': 1829.0} ,
{'Question': 'Kiedy Clinton został po raz pierwszy wybrany na prezydenta USA.?', 'Answer': 1992.0} ,
{'Question': 'Kiedy po raz pierwszy zdobyto Mount Everest?', 'Answer': 1953.0} ,
{'Question': 'Kiedy urodził się Sean Connery?', 'Answer': 1930.0} ,
{'Question': 'Kiedy wprowadzono apartheid w południowej afryce?', 'Answer': 1948.0} ,
{'Question': 'Kiedy zbudowano pałac Buckingham?', 'Answer': 1703.0} ,
{'Question': 'Kiedy opatentowano gumę do żucia?', 'Answer': 1869.0} ,
{'Question': 'Kiedy został zniszczony kryształowy pałac?', 'Answer': 1936.0} ,
{'Question': 'Kiedy wynaleziono aromatyzowaną wodę sodową?', 'Answer': 1807.0} ,
{'Question': 'Kiedy wynaleziono oświetlenie gazowe?', 'Answer': 1792.0} ,
{'Question': 'Kiedy George Jones został włączony do Country Music Hall of Fame?', 'Answer': 1992.0} ,
{'Question': 'Kiedy odkryto insulinę?', 'Answer': 1922.0} ,
{'Question': 'Kiedy nelson mandela został zwolniony z więzienia?', 'Answer': 1990.0} ,
{'Question': 'Kiedy nelson mandela został wypuszczony z wyspy robben?', 'Answer': 1990.0} ,
{'Question': 'Kiedy wzniesiono mur berliński?', 'Answer': 1961.0} ,
{'Question': 'Kiedy ukończono budowę wieży Eiffla?', 'Answer': 1859.0} ,
{'Question': 'Kiedy zjednoczył się parlament angielski i szkocki?', 'Answer': 1707.0} ,
{'Question': 'Kiedy powstała partia faszystowska we Włoszech?', 'Answer': 1919.0} ,
{'Question': 'Kiedy odbyła się ekspedycja Kon-Tiki?', 'Answer': 1947.0} ,
{'Question': 'Kiedy miało miejsce włamanie do Watergate?', 'Answer': 1972.0} ,
{'Question': 'Kiedy wynaleziono adresograf?', 'Answer': 1892.0} ,
{'Question': 'Kiedy wynaleziono kaskadowy tuningowy odbiornik radiowy?', 'Answer': 1913.0} ,
{'Question': 'Kiedy wynaleziono kasę fiskalną?', 'Answer': 1879.0} ,
{'Question': 'Kiedy wynaleziono kineskop?', 'Answer': 1878.0} ,
{'Question': 'Kiedy wynaleziono głośnik dynamiczny?', 'Answer': 1924.0} ,
{'Question': 'Kiedy wynaleziono elektromagnes?', 'Answer': 1828.0} ,
{'Question': 'Kiedy powstała pierwsza gra "Final Fantasy"?', 'Answer': 1987.0} ,
{'Question': 'Kiedy odbył się pierwszy australijski tour krykietowy do Anglii?', 'Answer': 1868.0} ,
{'Question': 'Kiedy powstał pierwszy film Mad Max?', 'Answer': 1979.0} ,
{'Question': 'Kiedy został wybrany pierwszy czarnoskóry burmistrz Chicago?', 'Answer': 1983.0} ,
{'Question': 'Kiedy wydano pierwszą kartę kredytową?', 'Answer': 1900.0} ,
{'Question': 'Kiedy odbył się pierwszy lot samolotem odrzutowym?', 'Answer': 1941.0} ,
{'Question': 'Kiedy odbył się pierwszy duży wyścig drogowy z Paryża do Bordeaux?', 'Answer': 1895.0} ,
{'Question': 'Kiedy wystawiono pierwszą sztukę w londyńskim Globe Theatre?', 'Answer': 1599.0} ,
{'Question': 'Kiedy została proklamowana pierwsza republika Francji?', 'Answer': 1792.0} ,
{'Question': 'Kiedy zostało otwarte pierwsze podmiejskie centrum handlowe?', 'Answer': 1922.0} ,
{'Question': 'Kiedy urodziło się pierwsze dziecko w probówce?', 'Answer': 1978.0} ,
{'Question': 'Kiedy wynaleziono pierwszą szczoteczkę do zębów z włosiem?', 'Answer': 1498.0} ,
{'Question': 'Kiedy odbył się pierwszy transatlantycki lot solo?', 'Answer': 1927.0} ,
{'Question': 'Kiedy wynaleziono turbinę gazową?', 'Answer': 1849.0} ,
{'Question': 'Kiedy wynaleziono lampę żarową?', 'Answer': 1879.0} ,
{'Question': 'Kiedy wynaleziono laser?', 'Answer': 1960.0} ,
{'Question': 'Kiedy ukończono budowę krzywej wieży w Pizie?', 'Answer': 1350.0} ,
{'Question': 'Kiedy wynaleziono telegraf magnetyczny?', 'Answer': 1837.0} ,
{'Question': 'Kiedy odbył się dziewiczy rejs statku "Titanic"?', 'Answer': 1912.0} ,
{'Question': 'Kiedy powstał konkurs miss world?', 'Answer': 1951.0} ,
{'Question': 'Kiedy po raz pierwszy ukazała się gazeta "pravda"?', 'Answer': 1912.0} ,
{'Question': 'Kiedy wynaleziono ogniwo fotoelektryczne?', 'Answer': 1895.0} ,
{'Question': 'Kiedy wynaleziono polaroidowy aparat fotograficzny?', 'Answer': 1948.0} ,
{'Question': 'Kiedy wynaleziono telegraf czterostronny (quadruplex)?', 'Answer': 1864.0} ,
{'Question': 'Kiedy wynaleziono ładowalny akumulator?', 'Answer': 1859.0} ,
{'Question': 'Kiedy miała miejsce rekordowa powódź na Morzu Północnym?', 'Answer': 1953.0} ,
{'Question': 'Kiedy odbyła się najkrótsza wojna w historii?', 'Answer': 1896.0} ,
{'Question': 'Kiedy wynaleziono czujnik dymu?', 'Answer': 1969.0} ,
{'Question': 'Kiedy odkryto bakterię gruźlicy?', 'Answer': 1932.0} ,
{'Question': 'Kiedy dokonano pierwszego na świecie przeszczepu serca u człowieka?', 'Answer': 1967.0} ,
{'Question': 'Kiedy po raz pierwszy sprzedano aparaty fotograficzne typu "instamatic?', 'Answer': 1968.0} ,
{'Question': 'Kiedy po raz pierwszy w Wielkiej Brytanii wprowadzono święta bankowe?', 'Answer': 1871.0} ,
{'Question': 'Kiedy wynaleziono sztuczne rzęsy?', 'Answer': 1916.0} ,
{'Question': 'Kiedy wynaleziono ciasteczka z wróżbą?', 'Answer': 1918.0} ,
{'Question': 'Którą olimpiadę zbojkotowały Stany Zjednoczone?', 'Answer': 980.0} ,
{'Question': 'Którą olimpiadę zbojkotowały Stany Zjednoczone?', 'Answer': 1980.0} ,
{'Question': "W którym roku wystrzelono orbitujący teleskop Hubble'a?", 'Answer': 1990.0} ,
{'Question': 'Która książka zawiera stwierdzenie "wszystkie świnie są równe, ale niektóre świnie są równiejsze od innych"?', 'Answer': 1984.0} ,
{'Question': 'Który izotop węgla jest używany do datowania (podaj numer) ?', 'Answer': 14.0} ,
{'Question': 'W której powieści występuje pokój 101?', 'Answer': 1984.0} ,
{'Question': 'W którym roku zmarli Nasser i De Gaulle, a Allende został wybrany na prezydenta Chile?', 'Answer': 1970.0} ,
{'Question': 'W którym roku Jemima Goldsmith poślubiła Imrama Kahna?', 'Answer': 1995.0} ,
{'Question': 'W którym roku doszło do masakry w dniu św.?', 'Answer': 1929.0} ,
{'Question': 'W którym roku odbyły się Igrzyska Olimpijskie "Jesse Owens?', 'Answer': 1936.0} ,
{'Question': 'W którym roku odbyły się Igrzyska Olimpijskie Jesse Owensa?', 'Answer': 1936.0} ,
{'Question': 'W którym roku William Golding otrzymał literacką Nagrodę Nobla?', 'Answer': 1983.0} ,
{'Question': 'Wilhelm Pierwszy został koronowany w Boże Narodzenie, ale w którym roku?', 'Answer': 1066.0} ,
{'Question': 'W ramach rodziny jastrzębiowatych, czyli ptaków drapieżnych, istnieje __________ gatunków orłów, jastrzębi, latawców i sępów Starego Świata, które występują niemal na całym świecie.?', 'Answer': 208.0} ,
{'Question': 'Kobiety spalają tłuszcz wolniej niż mężczyźni, w tempie około ile kalorii dziennie?', 'Answer': 50.0} ,
{'Question': 'Yasser Arafat był przywódcą OWP od którego roku?', 'Answer': 1969.0} ,
{'Question': 'Rok, w którym urodził się Marcin Luter?', 'Answer': 1483.0} ,
{'Question': 'Rok, w którym odbyła się bitwa pod Bałakławą?', 'Answer': 1854.0} ,
{'Question': 'Rok pierwszego załogowego lotu w kosmos?', 'Answer': 1961.0} ,
{'Question': 'Rok, w którym Viking I wylądował na Marsie?', 'Answer': 1976.0} ,
{'Question': 'Płeć konia można poznać po jego zębach. Większość samców ma ich 40, samice mają __________?', 'Answer': 36.0} ,
{'Question': 'Ręcznie można wydoić około __________ krów na godzinę, ale przy użyciu nowoczesnych maszyn można wydoić do 100 krów na godzinę.?', 'Answer': 6.0} ,
{'Question': '__________ Szynszyle zostały przywiezione z Andów w Ameryce Południowej w latach 30-tych XX wieku. Wszystkie szynszyle żyjące obecnie w Ameryce Północnej wywodzą się od tych __________ szynszyli.?', 'Answer': 11.0} ,
]

  $(function () {
    const randomElement = questions[Math.floor(Math.random() * questions.length)];
    question = randomElement['Question']
    number = randomElement['Answer']
    $('#question').text(question);
    $('#number').text(number);
  });
$(document).on('click', '#btn', function () {
  $('#number').toggle()
});

$(document).on('click', '#reloadbtn', function () {
  window.location.reload(true);
});